### ISSUE TITLE
AttributeError: SetInput

### ISSUE THREAD

**Issue by nilswagner** [nschloe/meshio#10]
meshio-convert screw.msh screw.vtu
Traceback (most recent call last):
  File "/home/nils/local/bin/meshio-convert", line 64, in <module>
    _main()
  File "/home/nils/local/bin/meshio-convert", line 25, in _main
    field_data=field_data
  File "/home/nils/local/lib/python2.7/site-packages/meshio/__init__.py", line 84, in write
    field_data=field_data
  File "/home/nils/local/lib/python2.7/site-packages/meshio/vtk_io.py", line 204, in write
    writer.SetInput(vtk_mesh)
AttributeError: SetInput

**Comment by nilswagner** [comment]
It works fine for me if I use

    writer.SetInputData(vtk_mesh)

instead of

    writer.SetInput(vtk_mesh)

**Comment by nschloe** [comment]
Ah okay; this must have changed between VTK versions. Workaround in PR https://github.com/nschloe/meshio/pull/11.

**Comment by nschloe** [comment]
Merged into master.
