### ISSUE TITLE
KeyError when opening `.vtu` file.

### ISSUE THREAD

**Issue by Alex-Muirhead** [nschloe/meshio#1072]
| Software | Version |
| :--- | :---: |
| Python | 3.9.2 |
| meshio | 4.3.12 |

Whenever I attempt to use `meshio` with [this attached](https://github.com/nschloe/meshio/files/6321803/cone-b0000-t0004.zip) `.vtu` file, it gives the following error/s
- In the command line
```zsh
> meshio-info cone-b0000-t0004.vtu
Traceback (most recent call last):
  File "/home/alex/miniconda/envs/meshio/bin/meshio-info", line 10, in <module>
    sys.exit(info())
  File "/home/alex/miniconda/envs/meshio/lib/python3.9/site-packages/meshio/_cli/_info.py", line 15, in info
    mesh = read(args.infile, file_format=args.input_format)
  File "/home/alex/miniconda/envs/meshio/lib/python3.9/site-packages/meshio/_helpers.py", line 69, in read
    return reader_map[file_format](filename)
  File "/home/alex/miniconda/envs/meshio/lib/python3.9/site-packages/meshio/vtu/_vtu.py", line 642, in read
    reader = VtuReader(filename)
  File "/home/alex/miniconda/envs/meshio/lib/python3.9/site-packages/meshio/vtu/_vtu.py", line 388, in __init__
    if root.attrib["version"] not in ["0.1", "1.0"]:
KeyError: 'version'
```
- In Python
```pycon
>>> import meshio
>>> meshio.read('cone-b0000-t0004.vtu')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/alex/miniconda/envs/meshio/lib/python3.9/site-packages/meshio/_helpers.py", line 69, in read
    return reader_map[file_format](filename)
  File "/home/alex/miniconda/envs/meshio/lib/python3.9/site-packages/meshio/vtu/_vtu.py", line 642, in read
    reader = VtuReader(filename)
  File "/home/alex/miniconda/envs/meshio/lib/python3.9/site-packages/meshio/vtu/_vtu.py", line 388, in __init__
    if root.attrib["version"] not in ["0.1", "1.0"]:
KeyError: 'version'
```

The attached `.vtu` file opens fine within Paraview, so it is my assumption that the file format is entirely valid.

**Comment by nschloe** [comment]
Strictly speaking, it's invalid VTU, but let's not be more catholic than the pope here. Fixed now.
