### ISSUE TITLE
Error convert .dat to .obj

### ISSUE THREAD

**Issue by louisdehaybe** [nschloe/meshio#1106]
Hi,

I'm trying to convert a .dat file to .obj file with the comand-line:
meshio-convert    input.dat output.obj

And I get the error:
`Traceback (most recent call last):
  File "C:\Users\Louis\anaconda3\envs\test_pybullet\Scripts\meshio-convert-script.py", line 9, in <module>
    sys.exit(convert())
  File "C:\Users\Louis\anaconda3\envs\test_pybullet\lib\site-packages\meshio\_cli\_convert.py", line 15, in convert
    mesh = read(args.infile, file_format=args.input_format)
  File "C:\Users\Louis\anaconda3\envs\test_pybullet\lib\site-packages\meshio\_helpers.py", line 69, in read
    return reader_map[file_format](filename)
  File "C:\Users\Louis\anaconda3\envs\test_pybullet\lib\site-packages\meshio\tecplot\_tecplot.py", line 104, in read
    out = read_buffer(f)
  File "C:\Users\Louis\anaconda3\envs\test_pybullet\lib\site-packages\meshio\tecplot\_tecplot.py", line 183, in read_buffer
    if zone_format == "FEBLOCK"
UnboundLocalError: local variable 'zone_format' referenced before assignment`

Would you have an idea please? 

The file is:
[input.zip](https://github.com/nschloe/meshio/files/6542695/input.zip)

Thanks a lot. 
Louis

**Comment by keurfonluu** [comment]
Hi,

``.dat`` files are associated to Tecplot format by default in ``meshio``.
Your input file is a Nastran file so you should specify the input file format so that the correct reader is called by ``meshio-convert``.

```
meshio-convert input.dat output.obj -i nastran
```

However, your mesh contains `"triangle6`" cells which is not supported by the ``.obj`` format.

**Comment by louisdehaybe** [comment]
Thank you very much, it worked with the command line you provided and with "CQUAD4" elements.
