### ISSUE TITLE
Issues reading vtu files generated by amrvac

### ISSUE THREAD

**Issue by OliverLew** [nschloe/meshio#1135]
I ran into two issues while trying to read vtu files generated by [amrvac](https://github.com/amrvac/amrvac).

1. With the vtu file [vaclogo0000.vtu.zip](https://github.com/nschloe/meshio/files/6668265/vaclogo0000.vtu.zip), if I run

```
meshio-info vaclogo0000.vtu
```

There will be an error:
```
Traceback (most recent call last):
  File "/home/xlu/.local/lib/python3.7/site-packages/meshio/vtu/_vtu.py", line 290, in __init__
    tree = ET.parse(str(filename), parser)
  File "/usr/local/anaconda3/lib/python3.7/xml/etree/ElementTree.py", line 1197, in parse
    tree.parse(source, parser)
  File "/usr/local/anaconda3/lib/python3.7/xml/etree/ElementTree.py", line 604, in parse
    parser.feed(data)
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 461, column 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xlu/.local/bin/meshio-info", line 8, in <module>
    sys.exit(info())
  File "/home/xlu/.local/lib/python3.7/site-packages/meshio/_cli/_info.py", line 15, in info
    mesh = read(args.infile, file_format=args.input_format)
  File "/home/xlu/.local/lib/python3.7/site-packages/meshio/_helpers.py", line 69, in read
    return reader_map[file_format](filename)
  File "/home/xlu/.local/lib/python3.7/site-packages/meshio/vtu/_vtu.py", line 554, in read
    reader = VtuReader(filename)
  File "/home/xlu/.local/lib/python3.7/site-packages/meshio/vtu/_vtu.py", line 293, in __init__
    root = _parse_raw_binary(str(filename))
  File "/home/xlu/.local/lib/python3.7/site-packages/meshio/vtu/_vtu.py", line 252, in _parse_raw_binary
    da_tag.set("offset", "%d" % len(arrays))
AttributeError: 'NoneType' object has no attribute 'set'
```

I am able to trace the issue to this line:
https://github.com/nschloe/meshio/blob/e7629defb191979925305df3fdf2ba6c19485448/src/meshio/vtu/_vtu.py#L251

The problem is that the generated vtu file has spaces in `offset` attribute:
```
<DataArray type="Float32" Name="rho" format="appended" offset="               0">
```

Removing the spaces will fix the error.

**So, is this format standard?** Should either side change their code, meshio or amrvac?

2. After removing the spaces that cause the first error, if I run

```
meshio-info vaclogo0000.nospaces.vtu
```

There will be another error:
```
Traceback (most recent call last):
  File "/home/oliver/.local/bin/meshio-info", line 8, in <module>
    sys.exit(info())
  File "/home/oliver/.local/lib/python3.9/site-packages/meshio/_cli/_info.py", line 15, in info
    mesh = read(args.infile, file_format=args.input_format)
  File "/home/oliver/.local/lib/python3.9/site-packages/meshio/_helpers.py", line 69, in read
    return reader_map[file_format](filename)
  File "/home/oliver/.local/lib/python3.9/site-packages/meshio/vtu/_vtu.py", line 555, in read
    reader = VtuReader(filename)
  File "/home/oliver/.local/lib/python3.9/site-packages/meshio/vtu/_vtu.py", line 369, in __init__
    pts = self.read_data(data_array)
  File "/home/oliver/.local/lib/python3.9/site-packages/meshio/vtu/_vtu.py", line 550, in read_data
    data = data.reshape(-1, int(c.attrib["NumberOfComponents"]))
ValueError: cannot reshape array of size 100 into shape (3)
```
I added a print command `print(data, data.shape, c.attrib)` before the reshape command (line 550) and it prints the following just before the error
```
[0.5 0.5 0.5 2.  2.  2.  2.  2.  2.  2.  0.5 0.5 0.5 2.  2.  2.  2.  2.
 2.  2.  0.5 0.5 2.  2.  2.  2.  2.  2.  2.  2.  0.5 0.5 2.  2.  2.  2.
 2.  2.  2.  2.  0.5 0.5 2.  2.  2.  2.  2.  2.  2.  2.  0.5 0.5 2.  2.
 2.  2.  2.  2.  2.  2.  0.5 2.  2.  2.  2.  2.  2.  2.  2.  2.  0.5 2.
 2.  2.  2.  2.  2.  2.  2.  2.  0.5 2.  2.  2.  2.  2.  2.  2.  2.  2.
 2.  2.  2.  2.  2.  2.  2.  2.  2.  2. ] (100,) {'type': 'Float32', 'NumberOfComponents': '3', 'format': 'appended', 'offset': '427932'}
```

Everything before that does not have any errors.

Is this a parsing error on the meshio side, or a data exporting error of amrvac?

**Comment by nschloe** [comment]
Interesting. I added better error messages in #1136, but the spacing issue cannot easily be resolved due to a shortcoming in Python's own XML parser. I haven't had time to look at the other error yet.

**Comment by OliverLew** [comment]
It's all right. I'll look more into it, and ask the devs of amrvac as well.

**Comment by brizzer** [comment]
Hello, I'm having the same issue (ValueError: cannot reshape array of size 106 into shape (3)) when reading some vtu files created by elmerfem. Oddly enough it only happens occasionally, The file opens in paraview so I belive that the error is in meshio.

Here are two files, on that work and on that doesn't (with slightly different mesh sizes), both exported from elmerfem:
[meshio_vtu_error.zip](https://github.com/nschloe/meshio/files/7219890/meshio_vtu_error.zip)

**Comment by nschloe** [comment]
@brizzer The file is in fact corrupt; the `Number Of Components` in `strain_yy` is wrong, and the data for `displacement` is wrong, too. I've added a better warning/error message.

**Comment by nschloe** [comment]
@OliverLew Have the amrvac devs fix this yet?

**Comment by OliverLew** [comment]
Probably not, I'll try again at some time. Also, I was only using these for class, now I have not paid attention for a while.

Revisiting the posts, I think the problem should be on amrvac's side, e.g. the export format and data array length. If you were cleaning up issues, maybe this one can be closed (should you want to).
