### ISSUE TITLE
issue when trying to convert a .f3grid file with 16 millions elements to .vtu

### ISSUE THREAD

**Issue by kuateric** [nschloe/meshio#1144]
I receive the following error when trying to convert very big files with meshio: 

```bat
meshio-convert test.f3grid test.vtu
Traceback (most recent call last):
  File "/home/eric/sources/anaconda3/bin/meshio-convert", line 8, in <module>
    sys.exit(convert())
  File "/home/eric/sources/anaconda3/lib/python3.8/site-packages/meshio/_cli/_convert.py", line 15, in convert
    mesh = read(args.infile, file_format=args.input_format)
  File "/home/eric/sources/anaconda3/lib/python3.8/site-packages/meshio/_helpers.py", line 69, in read
    return reader_map[file_format](filename)
  File "/home/eric/sources/anaconda3/lib/python3.8/site-packages/meshio/flac3d/_flac3d.py", line 103, in read
    out = read_buffer(f, binary)
  File "/home/eric/sources/anaconda3/lib/python3.8/site-packages/meshio/flac3d/_flac3d.py", line 166, in read_buffer
    pid, point = _read_point(line, binary)
  File "/home/eric/sources/anaconda3/lib/python3.8/site-packages/meshio/flac3d/_flac3d.py", line 219, in _read_point
    pid = int(buf_or_line[1])
ValueError: invalid literal for int() with base 10: '1,'
```

How much elements meshio can process ? If the number of elements is limited, it would be great to increase that. I would be grateful for any help

**Comment by kuateric** [comment]
sorry, it works fine. There was a problem in the input file.
