### ISSUE TITLE
Problem with Face groups of FLac3d (v6) exported .f3grid mesh to convert

### ISSUE THREAD

**Issue by alisheikholeslam** [nschloe/meshio#1152]
Hello dear developers,
I have used meshio for several times to convert Flac3d mesh files to other versions without any problem. For my new required mesh, which face groups have been defined, an error is appeared as below:

> Traceback (most recent call last):
  File "C:/Users/Ali/Desktop/Mesh convertion.py", line 8, in <module>
    mesh = meshio.read(str(os.path.join(os.environ['USERPROFILE'], "Desktop", "sd.f3grid")))
  File "C:\Users\Ali\anaconda3\envs\PFC_FiPy\lib\site-packages\meshio\_helpers.py", line 69, in read
    return reader_map[file_format](filename)
  File "C:\Users\Ali\anaconda3\envs\PFC_FiPy\lib\site-packages\meshio\flac3d\_flac3d.py", line 103, in read
    out = read_buffer(f, binary)
  File "C:\Users\Ali\anaconda3\envs\PFC_FiPy\lib\site-packages\meshio\flac3d\_flac3d.py", line 178, in read_buffer
    name, slot, data = _read_group(f, binary, line)
  File "C:\Users\Ali\anaconda3\envs\PFC_FiPy\lib\site-packages\meshio\flac3d\_flac3d.py", line 269, in _read_group
    data += [int(l) for l in line]
  File "C:\Users\Ali\anaconda3\envs\PFC_FiPy\lib\site-packages\meshio\flac3d\_flac3d.py", line 269, in <listcomp>
    data += [int(l) for l in line]
ValueError: invalid literal for int() with base 10: 'FGROUP'

This mesh file have exported from Flac version 6, not 3Dec or Udec as it was in #839.
My meshio version is 4.4.6, which is latest version that will be installed by forge conda.
I coudn't convert the attached mesh [Core.zip](https://github.com/nschloe/meshio/files/6857427/Core.zip) to .msh format and would be appreciated if you could help to solve the problem.

Best regards,
Ali Sheikholeslam

**Comment by alisheikholeslam** [comment]
I have tested again with changing the related codes in meshio _flac3d.py as the changed codes that are written for #1153 without any problem.
Please inform me if the correction is verified to close the issue, if it needs to be closed by me.
Thanks all.
