### ISSUE TITLE
error passing from "ansys .msh" file to "gmsh .msh" file 

### ISSUE THREAD

**Issue by ruffi92** [nschloe/meshio#1211]
Hi to all, i'm trying to convert a .msh file coming from an ANSYS simulation into native .msh in order to upload it on GMSH. 
In terminal i write this statement: 
```
meshio convert  --input-format ansys --output-format gmsh  /Users/luckyman/Desktop/CoreFull_NoGrid.msh output.msh
```
but appear the following error message: 

```
**Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/bin/meshio", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/meshio/_cli/_main.py", line 53, in main
    return args.func(args)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/meshio/_cli/_convert.py", line 93, in convert
    write(args.outfile, mesh, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/meshio/_helpers.py", line 142, in write
    return writer(filename, mesh, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/meshio/gmsh/main.py", line 111, in <lambda>
    "gmsh": lambda f, m, **kwargs: write(f, m, "4.1", **kwargs),
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/meshio/gmsh/main.py", line 102, in write
    writer.write(filename, mesh, binary=binary, float_fmt=float_fmt)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/meshio/gmsh/_gmsh41.py", line 341, in write
    _write_nodes(fh, mesh.points, mesh.cells, mesh.point_data, float_fmt, binary)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/meshio/gmsh/_gmsh41.py", line 601, in _write_nodes
    raise WriteError(
meshio._exceptions.WriteError: Specify entity information (gmsh:dim_tags in point_data) to deal with more than one cell type.** 
```
in particolar i don't understand the last part ( "specify entity information"), what i have to add exactly? 

Thanks for any help!

**Comment by gdmcbain** [comment]
Gmsh has revised its MSH format over many years. There are a couple of important versions, MSH 2.2 and MSH 4.1 which are very different.  MSH 4.1 is hard to write; meshio cannot yet write arbitrary MSH 4.1. Try writing MSH 2.2; it's much easier and meshio does a good job.

This issue is a duplicate. I'll link to the original later. There are also several other issues on this list relating to the difficulty of writing MSH 4.1 "entities".

**Comment by nschloe** [comment]
The dup is #865.
