### ISSUE TITLE
[BUG] Cell type "wedge15" is missing from the _mesh.topological_dimension dictionary

### ISSUE THREAD

**Issue by aaguirreme** [nschloe/meshio#1247]
In version 5.2.2, meshio cannot create nor write meshes involving the cell type "wedge15" due to a missing entry in `_mesh.topological_dimension` dictionary.

**To Reproduce**

Executing the Python script below raises a KeyError exception due to the missing "wedge15" key:

```Python
import meshio

points = [[0.0, 0.0, 0.0], [1.0, 0.0, 0.0], [0.0, 1.0, 0.0],
          [0.0, 0.0, 1.0], [1.0, 0.0, 1.0], [0.0, 1.0, 1.0],
          [0.5, 0.0, 0.0], [0.5, 0.5, 0.0], [0.0, 0.5, 0.0],
          [0.5, 0.0, 1.0], [0.5, 0.5, 1.0], [0.0, 0.5, 1.0],
          [0.0, 0.0, 0.5], [1.0, 0.0, 0.5], [0.0, 1.0, 0.5]]

cells = [('wedge15', [[k for k in range(15)]])]

mesh = meshio.Mesh(points, cells)
```

```
$ python3 foo.py
Traceback (most recent call last):
  File "foo.py", line 13, in <module>
    mesh = meshio.Mesh(points, cells)
  File "/home/user/.local/lib/python3.7/site-packages/meshio/_mesh.py", line 150, in __init__
    data if cell_type.startswith("polyhedron") else np.asarray(data),
  File "/home/user/.local/lib/python3.7/site-packages/meshio/_mesh.py", line 99, in __init__
    self.dim = topological_dimension[cell_type]
KeyError: 'wedge15'
```

**Diagnose**
```
$ pip freeze | grep meshio
meshio==5.2.2
```

**Comment by imirzov** [comment]
Thank you for the tool. It's awesome! But I've got a problem:
```
ihor@alkor:~$ python -V
Python 3.10.6

ihor@alkor:~$ python -m pip install meshio
Defaulting to user installation because normal site-packages is not writeable
Collecting meshio
  Downloading meshio-5.3.4-py3-none-any.whl (167 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 167.7/167.7 KB 2.9 MB/s eta 0:00:00
Requirement already satisfied: rich in ./.local/lib/python3.10/site-packages (from meshio) (12.5.1)
Requirement already satisfied: numpy in ./.local/lib/python3.10/site-packages (from meshio) (1.23.2)
Requirement already satisfied: pygments<3.0.0,>=2.6.0 in ./.local/lib/python3.10/site-packages (from rich->meshio) (2.13.0)
Requirement already satisfied: commonmark<0.10.0,>=0.9.0 in ./.local/lib/python3.10/site-packages (from rich->meshio) (0.9.1)
Installing collected packages: meshio
Successfully installed meshio-5.3.4

ihor@alkor:~$ meshio convert default_original.inp default_original.med
Traceback (most recent call last):
  File "/home/ihor/.local/bin/meshio", line 8, in <module>
    sys.exit(main())
  File "/home/ihor/.local/lib/python3.10/site-packages/meshio/_cli/_main.py", line 52, in main
    return args.func(args)
  File "/home/ihor/.local/lib/python3.10/site-packages/meshio/_cli/_convert.py", line 53, in convert
    mesh = read(args.infile, file_format=args.input_format)
  File "/home/ihor/.local/lib/python3.10/site-packages/meshio/_helpers.py", line 71, in read
    return _read_file(Path(filename), file_format)
  File "/home/ihor/.local/lib/python3.10/site-packages/meshio/_helpers.py", line 103, in _read_file
    return reader_map[file_format](str(path))
  File "/home/ihor/.local/lib/python3.10/site-packages/meshio/abaqus/_abaqus.py", line 106, in read
    out = read_buffer(f)
  File "/home/ihor/.local/lib/python3.10/site-packages/meshio/abaqus/_abaqus.py", line 144, in read_buffer
    cells.append(CellBlock(cell_type, cells_data))
  File "/home/ihor/.local/lib/python3.10/site-packages/meshio/_mesh.py", line 99, in __init__
    self.dim = topological_dimension[cell_type]
KeyError: 'wedge15'
```
