### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by preynier** [nschloe/meshio#1256]
I run the command:
pip install meshio[all]

as indicated on the website, I have got:

Downloading/unpacking meshio[all]
  Downloading meshio-5.2.2-py3-none-any.whl (165kB): 165kB downloaded
Downloading/unpacking rich (from meshio[all])
  Downloading rich-10.16.2-py3-none-any.whl (214kB): 214kB downloaded
Requirement already satisfied (use --upgrade to upgrade): numpy in /usr/lib64/python3.4/site-packages (from meshio[all])
Downloading/unpacking importlib-metadata (from meshio[all])
  Downloading importlib_metadata-4.10.0-py3-none-any.whl
Downloading/unpacking h5py (from meshio[all])
  Downloading h5py-3.6.0.tar.gz (384kB): 384kB downloaded
  Running setup.py (path:/tmp/pip_build_root/h5py/setup.py) egg_info for package h5py
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_root/h5py/setup.py", line 20, in <module>
        import setup_build, setup_configure
      File "/tmp/pip_build_root/h5py/setup_build.py", line 18, in <module>
        import api_gen
      File "/tmp/pip_build_root/h5py/api_gen.py", line 113
        self.err_value = f"<{self.code}>NULL"
                                            ^
    SyntaxError: invalid syntax
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_root/h5py/setup.py", line 20, in <module>

    import setup_build, setup_configure

  File "/tmp/pip_build_root/h5py/setup_build.py", line 18, in <module>

    import api_gen

  File "/tmp/pip_build_root/h5py/api_gen.py", line 113

    self.err_value = f"<{self.code}>NULL"

                                        ^

SyntaxError: invalid syntax

May you help please ? 
Thanks Philippe

**Comment by preynier** [comment]
As indicated I tried: pip install meshio
and ....

 pip install meshio
Downloading/unpacking meshio
  Downloading meshio-5.2.2-py3-none-any.whl (165kB): 165kB downloaded
Downloading/unpacking importlib-metadata (from meshio)
  Downloading importlib_metadata-4.10.0-py3-none-any.whl
Downloading/unpacking rich (from meshio)
  Downloading rich-11.0.0-py3-none-any.whl (215kB): 215kB downloaded
Requirement already satisfied (use --upgrade to upgrade): numpy in /usr/lib64/python3.4/site-packages (from meshio)
Downloading/unpacking zipp>=0.5 (from importlib-metadata->meshio)
  Downloading zipp-3.7.0-py3-none-any.whl
Downloading/unpacking typing-extensions>=3.6.4 (from importlib-metadata->meshio)
  Downloading typing_extensions-4.0.1-py3-none-any.whl
Downloading/unpacking pygments>=2.6.0,<3.0.0 (from rich->meshio)
  Downloading Pygments-2.11.2-py3-none-any.whl (1.1MB): 1.1MB downloaded
Downloading/unpacking commonmark>=0.9.0,<0.10.0 (from rich->meshio)
  Downloading commonmark-0.9.1-py2.py3-none-any.whl (51kB): 51kB downloaded
Downloading/unpacking colorama>=0.4.0,<0.5.0 (from rich->meshio)
  Downloading colorama-0.4.4-py2.py3-none-any.whl
Downloading/unpacking dataclasses>=0.7,<0.9 (from rich->meshio)
  Downloading dataclasses-0.8-py3-none-any.whl
Installing collected packages: meshio, importlib-metadata, rich, zipp, typing-extensions, pygments, commonmark, colorama, dataclasses
*** Error compiling '/tmp/pip_build_root/meshio/meshio/_cli/_ascii.py'...
  File "/tmp/pip_build_root/meshio/meshio/_cli/_ascii.py", line 27
    print(f"File size before: {size / 1024 ** 2:.2f} MB")
                                                       ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip_build_root/meshio/meshio/_cli/_binary.py'...
  File "/tmp/pip_build_root/meshio/meshio/_cli/_binary.py", line 26
    print(f"File size before: {size / 1024 ** 2:.2f} MB")
                                                       ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip_build_root/meshio/meshio/_cli/_compress.py'...
  File "/tmp/pip_build_root/meshio/meshio/_cli/_compress.py", line 33
    print(f"File size before: {size / 1024 ** 2:.2f} MB")
                                                       ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip_build_root/meshio/meshio/_cli/_decompress.py'...
  File "/tmp/pip_build_root/meshio/meshio/_cli/_decompress.py", line 26
    print(f"File size before: {size / 1024 ** 2:.2f} MB")
                                                       ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip_build_root/meshio/meshio/_cli/_main.py'...
  File "/tmp/pip_build_root/meshio/meshio/_cli/_main.py", line 57
    python_version = f"{version_info.major}.{version_info.minor}.{version_info.micro}"
                                                                                     ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip_build_root/meshio/meshio/_common.py'...
  File "/tmp/pip_build_root/meshio/meshio/_common.py", line 125
    f"[yellow][bold]Warning:[/bold] {string}[/yellow]", highlight=highlight
                                                     ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip_build_root/meshio/meshio/_cxml/etree.py'...
  File "/tmp/pip_build_root/meshio/meshio/_cxml/etree.py", line 25
    kw_list = [f'{key}="{value}"' for key, value in self.attrib.items()]
                                ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip_build_root/meshio/meshio/_helpers.py'...
  File "/tmp/pip_build_root/meshio/meshio/_helpers.py", line 36
    raise ReadError(f"Could not deduce file format from extension '{ext}'.")
                                                                          ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip_build_root/meshio/meshio/_mesh.py'...
  File "/tmp/pip_build_root/meshio/meshio/_mesh.py", line 106
    f"type: {self.type}",
                       ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip_build_root/meshio/meshio/_vtk_common.py'...
  File "/tmp/pip_build_root/meshio/meshio/_vtk_common.py", line 95
    raise ReadError(f"len(offsets) != len(types) ({len(offsets)} != {len(types)})")
                                                                                 ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip_build_root/meshio/meshio/abaqus/_abaqus.py'...
  File "/tmp/pip_build_root/meshio/meshio/abaqus/_abaqus.py", line 179
    raise ReadError(f"Unknown cell set '{set_name}'")
                                                   ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip_build_root/meshio/meshio/ansys/_ansys.py'...
  File "/tmp/pip_build_root/meshio/meshio/ansys/_ansys.py", line 84
    ReadError(f"Expected keys '20' or '30', got {out.group(1)}.")
                                                               ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip_build_root/meshio/meshio/avsucd/_avsucd.py'...
  File "/tmp/pip_build_root/meshio/meshio/avsucd/_avsucd.py", line 156
    f.write(f"# Written by meshio v{version}\n")
                                              ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip_build_root/meshio/meshio/dolfin/_dolfin.py'...
  File "/tmp/pip_build_root/meshio/meshio/dolfin/_dolfin.py", line 46
    cell_tags = [f"v{i}" for i in range(num_nodes_per_cell)]
                       ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip_build_root/meshio/meshio/exodus/_exodus.py'...
  File "/tmp/pip_build_root/meshio/meshio/exodus/_exodus.py", line 267
    rootgrp.title = f"Created by meshio v{__version__}, {now}"
                                                             ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip_build_root/meshio/meshio/flac3d/_flac3d.py'...
  File "/tmp/pip_build_root/meshio/meshio/flac3d/_flac3d.py", line 94
    return {**a, **b}
             ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip_build_root/meshio/meshio/gmsh/_gmsh22.py'...
  File "/tmp/pip_build_root/meshio/meshio/gmsh/_gmsh22.py", line 50
    raise ReadError(f"Unexpected line {repr(line)}")
                                                  ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip_build_root/meshio/meshio/gmsh/_gmsh40.py'...
  File "/tmp/pip_build_root/meshio/meshio/gmsh/_gmsh40.py", line 245
    fh.write(f"$MeshFormat\n4.0 {mode_idx} {size_of_double}\n".encode())
                                                             ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip_build_root/meshio/meshio/gmsh/_gmsh41.py'...
  File "/tmp/pip_build_root/meshio/meshio/gmsh/_gmsh41.py", line 31
    return np.dtype(f"u{data_size}")
                                  ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip_build_root/meshio/meshio/gmsh/common.py'...
  File "/tmp/pip_build_root/meshio/meshio/gmsh/common.py", line 24
    if line.strip() == f"$End{block}":
                                    ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip_build_root/meshio/meshio/hmf/_hmf.py'...
  File "/tmp/pip_build_root/meshio/meshio/hmf/_hmf.py", line 89
    f"Topology{k}",
                 ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip_build_root/meshio/meshio/mdpa/_mdpa.py'...
  File "/tmp/pip_build_root/meshio/meshio/mdpa/_mdpa.py", line 379
    dimension_name = f"{dimension}D"
                                   ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip_build_root/meshio/meshio/med/_med.py'...
  File "/tmp/pip_build_root/meshio/meshio/med/_med.py", line 43
    raise ReadError(f"Must only contain exactly 1 mesh, found {len(meshes)}.")
                                                                            ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip_build_root/meshio/meshio/medit/_medit.py'...
  File "/tmp/pip_build_root/meshio/meshio/medit/_medit.py", line 153
    warn(f"meshio doesn't know {field_code[0]} type. Skipping.")
                                                              ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip_build_root/meshio/meshio/nastran/_nastran.py'...
  File "/tmp/pip_build_root/meshio/meshio/nastran/_nastran.py", line 231
    raise RuntimeError(f'unknown "{format}" format')
                                                  ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip_build_root/meshio/meshio/netgen/_netgen.py'...
  File "/tmp/pip_build_root/meshio/meshio/netgen/_netgen.py", line 140
    raise ValueError(f"Unknown Netgen cell section '{netgen_cell_type}'")
                                                                       ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip_build_root/meshio/meshio/obj/_obj.py'...
  File "/tmp/pip_build_root/meshio/meshio/obj/_obj.py", line 115
    f.write(f"v {p[0]} {p[1]} {p[2]}\n")
                                      ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip_build_root/meshio/meshio/off/_off.py'...
  File "/tmp/pip_build_root/meshio/meshio/off/_off.py", line 67
    warn(f"OFF only supports triangle cells. Skipping {string}.")
                                                               ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip_build_root/meshio/meshio/permas/_permas.py'...
  File "/tmp/pip_build_root/meshio/meshio/permas/_permas.py", line 142
    raise ReadError(f"Element type not available: {etype}")
                                                         ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip_build_root/meshio/meshio/ply/_ply.py'...
  File "/tmp/pip_build_root/meshio/meshio/ply/_ply.py", line 121
    raise ReadError(f"Expected positive num_cells (got `{num_cells}`.")
                                                                     ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip_build_root/meshio/meshio/stl/_stl.py'...
  File "/tmp/pip_build_root/meshio/meshio/stl/_stl.py", line 189
    warn(f"STL can only write triangle cells. Discarding {invalid}.")
                                                                   ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip_build_root/meshio/meshio/su2/_su2.py'...
  File "/tmp/pip_build_root/meshio/meshio/su2/_su2.py", line 78
    warn(f"meshio could not parse line\n {line}\n skipping.....")
                                                               ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip_build_root/meshio/meshio/svg/_svg.py'...
  File "/tmp/pip_build_root/meshio/meshio/svg/_svg.py", line 28
    f"SVG can only handle flat 2D meshes (shape: {mesh.points.shape})"
                                                                     ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip_build_root/meshio/meshio/tecplot/_tecplot.py'...
  File "/tmp/pip_build_root/meshio/meshio/tecplot/_tecplot.py", line 234
    var = f"{line[i]}_{line[i + 1]}"
                                   ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip_build_root/meshio/meshio/tetgen/_tetgen.py'...
  File "/tmp/pip_build_root/meshio/meshio/tetgen/_tetgen.py", line 55
    point_data[f"tetgen:attr{k + 1}"] = points[:, 4 + k]
                                   ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip_build_root/meshio/meshio/ugrid/_ugrid.py'...
  File "/tmp/pip_build_root/meshio/meshio/ugrid/_ugrid.py", line 195
    msg = f"UGRID mesh format doesn't know {key} cells. Skipping."
                                                                 ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip_build_root/meshio/meshio/vtk/_vtk_42.py'...
  File "/tmp/pip_build_root/meshio/meshio/vtk/_vtk_42.py", line 133
    raise ReadError(f"Unknown VTK data type '{data_type}'.")
                                                          ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip_build_root/meshio/meshio/vtk/_vtk_51.py'...
  File "/tmp/pip_build_root/meshio/meshio/vtk/_vtk_51.py", line 87
    raise ReadError(f"Unknown VTK data type '{data_type}'.")
                                                          ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip_build_root/meshio/meshio/vtu/_vtu.py'...
  File "/tmp/pip_build_root/meshio/meshio/vtu/_vtu.py", line 77
    key = f"polyhedron{num_nodes_this_cell}"
                                           ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip_build_root/meshio/meshio/wkt/_wkt.py'...
  File "/tmp/pip_build_root/meshio/meshio/wkt/_wkt.py", line 24
    tin_pattern = fr"TIN\s*\((?:\s*{triangle_pattern}\s*,?)*\s*\)"
                                                                 ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip_build_root/meshio/meshio/xdmf/main.py'...
  File "/tmp/pip_build_root/meshio/meshio/xdmf/main.py", line 50
    raise ReadError(f"Unknown XDMF version {version}.")
                                                     ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip_build_root/meshio/meshio/xdmf/time_series.py'...
  File "/tmp/pip_build_root/meshio/meshio/xdmf/time_series.py", line 39
    raise ReadError(f"Unknown XDMF version {version}.")
                                                     ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip_build_root/importlib-metadata/importlib_metadata/__init__.py'...
  File "/tmp/pip_build_root/importlib-metadata/importlib_metadata/__init__.py", line 55
    return f"No package metadata was found for {self.name}"
                                                          ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip_build_root/rich/rich/__init__.py'...
  File "/tmp/pip_build_root/rich/rich/__init__.py", line 14
    _console: Optional["Console"] = None
            ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip_build_root/rich/rich/__main__.py'...
  File "/tmp/pip_build_root/rich/rich/__main__.py", line 234
    print(f"rendered in {pre_cache_taken}ms (cold cache)")
                                                        ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip_build_root/rich/rich/_inspect.py'...
  File "/tmp/pip_build_root/rich/rich/_inspect.py", line 56
    ) -> None:
    ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip_build_root/rich/rich/_log_render.py'...
  File "/tmp/pip_build_root/rich/rich/_log_render.py", line 30
    self._last_time: Optional[Text] = None
                   ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip_build_root/rich/rich/_lru_cache.py'...
  File "/tmp/pip_build_root/rich/rich/_lru_cache.py", line 31
    value: CacheValue = OrderedDict.__getitem__(self, key)
         ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip_build_root/rich/rich/_ratio.py'...
  File "/tmp/pip_build_root/rich/rich/_ratio.py", line 15
    size: Optional[int] = None
        ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip_build_root/rich/rich/_timer.py'...
  File "/tmp/pip_build_root/rich/rich/_timer.py", line 19
    print(f"{subject} elapsed {elapsed_ms:.1f}ms")
                                                ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip_build_root/rich/rich/_windows.py'...
  File "/tmp/pip_build_root/rich/rich/_windows.py", line 9
    vt: bool = False
      ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip_build_root/rich/rich/_wrap.py'...
  File "/tmp/pip_build_root/rich/rich/_wrap.py", line 21
    divides: List[int] = []
           ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip_build_root/rich/rich/align.py'...
  File "/tmp/pip_build_root/rich/rich/align.py", line 50
    ) -> None:
    ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip_build_root/rich/rich/ansi.py'...
  File "/tmp/pip_build_root/rich/rich/ansi.py", line 16
    plain: str = ""
         ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip_build_root/rich/rich/bar.py'...
  File "/tmp/pip_build_root/rich/rich/bar.py", line 38
    ):
    ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip_build_root/rich/rich/box.py'...
  File "/tmp/pip_build_root/rich/rich/box.py", line 101
    parts: List[str] = []
         ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip_build_root/rich/rich/cells.py'...
  File "/tmp/pip_build_root/rich/rich/cells.py", line 124
    lines: List[List[str]] = [[]]
         ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip_build_root/rich/rich/color.py'...
  File "/tmp/pip_build_root/rich/rich/color.py", line 30
    return f"ColorSystem.{self.name}"
                                    ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip_build_root/rich/rich/color_triplet.py'...
  File "/tmp/pip_build_root/rich/rich/color_triplet.py", line 7
    red: int
       ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip_build_root/rich/rich/columns.py'...
  File "/tmp/pip_build_root/rich/rich/columns.py", line 43
    ) -> None:
    ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip_build_root/rich/rich/console.py'...
  File "/tmp/pip_build_root/rich/rich/console.py", line 113
    width: int
         ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip_build_root/rich/rich/containers.py'...
  File "/tmp/pip_build_root/rich/rich/containers.py", line 36
    self._renderables: List["RenderableType"] = (
                     ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip_build_root/rich/rich/control.py'...
  File "/tmp/pip_build_root/rich/rich/control.py", line 17
    CONTROL_CODES_FORMAT: Dict[int, Callable[..., str]] = {
                        ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip_build_root/rich/rich/default_styles.py'...
  File "/tmp/pip_build_root/rich/rich/default_styles.py", line 6
    DEFAULT_STYLES: Dict[str, Style] = {
                  ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip_build_root/rich/rich/emoji.py'...
  File "/tmp/pip_build_root/rich/rich/emoji.py", line 53
    raise NoEmoji(f"No emoji called {name!r}")
                                            ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip_build_root/rich/rich/file_proxy.py'...
  File "/tmp/pip_build_root/rich/rich/file_proxy.py", line 17
    self.__buffer: List[str] = []
                 ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip_build_root/rich/rich/filesize.py'...
  File "/tmp/pip_build_root/rich/rich/filesize.py", line 26
    ) -> str:
    ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip_build_root/rich/rich/highlighter.py'...
  File "/tmp/pip_build_root/rich/rich/highlighter.py", line 36
    raise TypeError(f"str or Text instance required, not {text!r}")
                                                                 ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip_build_root/rich/rich/json.py'...
  File "/tmp/pip_build_root/rich/rich/json.py", line 83
    json_instance: "JSON" = cls.__new__(cls)
                 ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip_build_root/rich/rich/jupyter.py'...
  File "/tmp/pip_build_root/rich/rich/jupyter.py", line 55
    fragments: List[str] = []
             ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip_build_root/rich/rich/layout.py'...
  File "/tmp/pip_build_root/rich/rich/layout.py", line 35
    region: Region
          ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip_build_root/rich/rich/live.py'...
  File "/tmp/pip_build_root/rich/rich/live.py", line 64
    ) -> None:
    ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip_build_root/rich/rich/live_render.py'...
  File "/tmp/pip_build_root/rich/rich/live_render.py", line 37
    self._shape: Optional[Tuple[int, int]] = None
               ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip_build_root/rich/rich/logging.py'...
  File "/tmp/pip_build_root/rich/rich/logging.py", line 46
    KEYWORDS: ClassVar[Optional[List[str]]] = [
            ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip_build_root/rich/rich/markdown.py'...
  File "/tmp/pip_build_root/rich/rich/markdown.py", line 21
    new_line: ClassVar[bool] = True
            ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip_build_root/rich/rich/markup.py'...
  File "/tmp/pip_build_root/rich/rich/markup.py", line 24
    name: str
        ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip_build_root/rich/rich/measure.py'...
  File "/tmp/pip_build_root/rich/rich/measure.py", line 14
    minimum: int
           ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip_build_root/rich/rich/padding.py'...
  File "/tmp/pip_build_root/rich/rich/padding.py", line 40
    ):
    ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip_build_root/rich/rich/palette.py'...
  File "/tmp/pip_build_root/rich/rich/palette.py", line 31
    caption=f"{len(self._colors)} colors",
                                        ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip_build_root/rich/rich/panel.py'...
  File "/tmp/pip_build_root/rich/rich/panel.py", line 55
    ) -> None:
    ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip_build_root/rich/rich/pretty.py'...
  File "/tmp/pip_build_root/rich/rich/pretty.py", line 199
    pprint: bool = True
          ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip_build_root/rich/rich/progress.py'...
  File "/tmp/pip_build_root/rich/rich/progress.py", line 121
    columns: List["ProgressColumn"] = (
           ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip_build_root/rich/rich/progress_bar.py'...
  File "/tmp/pip_build_root/rich/rich/progress_bar.py", line 55
    self._pulse_segments: Optional[List[Segment]] = None
                        ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip_build_root/rich/rich/prompt.py'...
  File "/tmp/pip_build_root/rich/rich/prompt.py", line 43
    response_type: type = str
                 ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip_build_root/rich/rich/protocol.py'...
  File "/tmp/pip_build_root/rich/rich/protocol.py", line 30
    rich_visited_set: Set[type] = set()  # Prevent potential infinite loop
                    ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip_build_root/rich/rich/region.py'...
  File "/tmp/pip_build_root/rich/rich/region.py", line 7
    x: int
     ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip_build_root/rich/rich/repr.py'...
  File "/tmp/pip_build_root/rich/rich/repr.py", line 47
    repr_str: List[str] = []
            ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip_build_root/rich/rich/rule.py'...
  File "/tmp/pip_build_root/rich/rich/rule.py", line 30
    ) -> None:
    ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip_build_root/rich/rich/scope.py'...
  File "/tmp/pip_build_root/rich/rich/scope.py", line 22
    ) -> "ConsoleRenderable":
    ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip_build_root/rich/rich/screen.py'...
  File "/tmp/pip_build_root/rich/rich/screen.py", line 26
    renderable: "RenderableType"
              ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip_build_root/rich/rich/segment.py'...
  File "/tmp/pip_build_root/rich/rich/segment.py", line 70
    text: str = ""
        ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip_build_root/rich/rich/spinner.py'...
  File "/tmp/pip_build_root/rich/rich/spinner.py", line 21
    ) -> None:
    ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip_build_root/rich/rich/status.py'...
  File "/tmp/pip_build_root/rich/rich/status.py", line 32
    ):
    ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip_build_root/rich/rich/style.py'...
  File "/tmp/pip_build_root/rich/rich/style.py", line 59
    _color: Optional[Color]
          ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip_build_root/rich/rich/syntax.py'...
  File "/tmp/pip_build_root/rich/rich/syntax.py", line 43
    ANSI_LIGHT: Dict[TokenType, Style] = {
              ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip_build_root/rich/rich/table.py'...
  File "/tmp/pip_build_root/rich/rich/table.py", line 42
    header: "RenderableType" = ""
          ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip_build_root/rich/rich/text.py'...
  File "/tmp/pip_build_root/rich/rich/text.py", line 35
    DEFAULT_JUSTIFY: "JustifyMethod" = "default"
                   ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip_build_root/rich/rich/theme.py'...
  File "/tmp/pip_build_root/rich/rich/theme.py", line 16
    styles: Dict[str, Style]
          ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip_build_root/rich/rich/traceback.py'...
  File "/tmp/pip_build_root/rich/rich/traceback.py", line 46
    ) -> Callable[[Type[BaseException], BaseException, Optional[TracebackType]], Any]:
    ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip_build_root/rich/rich/tree.py'...
  File "/tmp/pip_build_root/rich/rich/tree.py", line 32
    ) -> None:
    ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip_build_root/typing-extensions/typing_extensions.py'...
  File "/tmp/pip_build_root/typing-extensions/typing_extensions.py", line 33
    raise TypeError(f"{cls} is not a generic class")
                                                  ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip_build_root/pygments/pygments/lexers/chapel.py'...
  File "/tmp/pip_build_root/pygments/pygments/lexers/chapel.py", line 35
    type_modifiers = (*type_modifiers_par, *type_modifiers_mem)
                         ^
SyntaxError: can use starred expression only as assignment target

*** Error compiling '/tmp/pip_build_root/pygments/pygments/lexers/julia.py'...
  File "/tmp/pip_build_root/pygments/pygments/lexers/julia.py", line 75
    (words([*OPERATORS_LIST, *DOTTED_OPERATORS_LIST], suffix=operator_suffixes), Operator),
                       ^
SyntaxError: can use starred expression only as assignment target

*** Error compiling '/tmp/pip_build_root/dataclasses/dataclasses.py'...
  File "/tmp/pip_build_root/dataclasses/dataclasses.py", line 246
    f'name={self.name!r},'
    ^
SyntaxError: invalid syntax

Successfully installed meshio importlib-metadata rich zipp typing-extensions pygments commonmark colorama dataclasses
Cleaning up...

It said it is successfully installed, due to the error messages I doubt; however I tried converting a 2Dmesh from tecplot (dat format) to su2.

meshio convert mesh.dat mesh.su2
Traceback (most recent call last):
  File "/usr/bin/meshio", line 7, in <module>
    from meshio._cli import main
  File "/usr/lib/python3.4/site-packages/meshio/__init__.py", line 1, in <module>
    from . import (
  File "/usr/lib/python3.4/site-packages/meshio/_cli/__init__.py", line 1, in <module>
    from ._main import main
  File "/usr/lib/python3.4/site-packages/meshio/_cli/_main.py", line 57
    python_version = f"{version_info.major}.{version_info.minor}.{version_info.micro}"
                                                                                     ^
SyntaxError: invalid syntax

.....is there a solution ?

**Comment by preynier** [comment]
No ! 
The instruction: pip install meshio has been run instead of pip install meshio[all]
and after you have all the error messages.
