### ISSUE TITLE
Discarding unused cell types crashes with Python 3

### ISSUE THREAD

**Issue by massimiliano-leoni** [nschloe/meshio#131]
When converting a 3D mesh to dolfin XML format, the following traceback appears.

```
Cell data: physical, geometrical
Traceback (most recent call last):
  File "/usr/local/bin/meshio-convert", line 130, in <module>
    _main()
  File "/usr/local/bin/meshio-convert", line 70, in _main
    field_data=field_data
  File "/usr/local/lib/python3.5/dist-packages/meshio/helpers.py", line 170, in write
    dolfin_io.write(filename, points, cells, cell_data=cell_data)
  File "/usr/local/lib/python3.5/dist-packages/meshio/dolfin_io.py", line 245, in write
    _write_mesh(filename, points, cell_type, cells)
  File "/usr/local/lib/python3.5/dist-packages/meshio/dolfin_io.py", line 136, in _write_mesh
    discarded_cells.remove(cell_type)
AttributeError: 'dict_keys' object has no attribute 'remove'
```

With the Python 2 version, it works fine. The crash happens when the message `WARNING:root:DOLFIN XML can only handle one cell type at a time. Using tetra, discarding triangle.` should be printed instead.

**Comment by nschloe** [comment]
Thanks for the report! Fixed in #136.
