### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Florian-Wi** [nschloe/meshio#1317]
Hey,

I try to transform meshes from gmsh-format to xdmf with meshio. Got this error in several setups of varying meshes, codes (predefined function, step by step, ...) and the error appappeard after installation of a complete new anaconda environment. Error looks like: 
```
<generator object raw_from_cell_data.<locals>.<genexpr> at 0x7fc22aa3d5f0>
Traceback (most recent call last):
  File "mesh/transformmesh.py", line 12, in <module>
    ms.write("mesh.xdmf", triangle_msh)
  File "/home/florian/anaconda3/envs/secenv/lib/python3.8/site-packages/meshio/_helpers.py", line 144, in write
    return writer(filename, mesh, **kwargs)
  File "/home/florian/anaconda3/envs/secenv/lib/python3.8/site-packages/meshio/xdmf/main.py", line 518, in write
    XdmfWriter(*args, **kwargs)
  File "/home/florian/anaconda3/envs/secenv/lib/python3.8/site-packages/meshio/xdmf/main.py", line 346, in __init__
    self.cell_data(mesh.cell_data, grid)
  File "/home/florian/anaconda3/envs/secenv/lib/python3.8/site-packages/meshio/xdmf/main.py", line 488, in cell_data
    for name, data in raw.items():
AttributeError: 'NoneType' object has no attribute 'items'
```

**To Reproduce**
A minimal code example:
Mesh:
```
$MeshFormat
4.1 0 8
$EndMeshFormat
$Entities
5 5 1 0
1 0.0121 0 0 0 
2 0.01265 0.0005999999999999999 0 0 
3 0.0121 0.0023 0 0 
4 0.0121 0.0043 0 0 
5 0.009999999999999998 0.0043 0 0 
1 0.0121 0 0 0.01265 0.0005999999999999999 0 0 2 1 -2 
2 0.0121 0.0005999999999999999 0 0.01265 0.0023 0 0 2 2 -3 
3 0.0121 0.0023 0 0.0121 0.0043 0 0 2 3 -4 
4 0.009999999999999998 0.0043 0 0.0121 0.0043 0 0 2 4 -5 
5 0.009999999999999998 0 0 0.0121 0.0043 0 0 2 5 -1 
1 0.009999999999999998 0 0 0.01265 0.0043 0 0 5 1 2 3 4 5 
$EndEntities
$Nodes
11 5 1 5
0 1 0 1
1
0.0121 0 0
0 2 0 1
2
0.01265 0.0005999999999999999 0
0 3 0 1
3
0.0121 0.0023 0
0 4 0 1
4
0.0121 0.0043 0
0 5 0 1
5
0.009999999999999998 0.0043 0
1 1 0 0
1 2 0 0
1 3 0 0
1 4 0 0
1 5 0 0
2 1 0 0
$EndNodes
$Elements
11 13 1 13
0 1 15 1
1 1 
0 2 15 1
2 2 
0 3 15 1
3 3 
0 4 15 1
4 4 
0 5 15 1
5 5 
1 1 1 1
6 1 2 
1 2 1 1
7 2 3 
1 3 1 1
8 3 4 
1 4 1 1
9 4 5 
1 5 1 1
10 5 1 
2 1 2 3
11 4 5 3 
12 3 1 2 
13 1 3 5 
$EndElements
```
Code:
```
import meshio as ms
import numpy

msh= ms.read('mesh/mymesh.msh')
prune_z = True
cell_type = "triangle"
cells = msh.get_cells_type(cell_type)
#cell_data = msh.get_cell_data("gmsh:physical", cell_type)
points = msh.points[:,:2] if prune_z else mesh.points
triangle_msh = ms.Mesh(points=points, cells={cell_type: cells})
print(triangle_msh)
ms.write("mesh.xdmf", triangle_msh)
```

**Diagnose**
meshio==4.0.4

installing meshio 5.0.0 solved the problem. Just wanted to report, in case you want to clear this for 4.0.4.

**Comment by nschloe** [comment]
Does this occur for the latest version?

**Comment by Florian-Wi** [comment]
nope

**Comment by nschloe** [comment]
Then the bug has already be solved.
