### ISSUE TITLE
IndexError with msh2vtu

### ISSUE THREAD

**Issue by emartincb** [nschloe/meshio#1360]
Hello all,

I was trying to convert .msh file to vtu files with msh2vtu.py but when I run it, the terminal return this error:

--> python3 msh2vtu.py  mesh.msh

MeshIO 5.3.4 found, MSH2VTU was tested with MeshIO 4.4.8.
Newer version of MeshIO than supported. Backward compatibility may be missing!
MeshIO version > 5.0 brings relevant changes. MSH2VTU will catch up as PyVista does so.
##

Original mesh (read)
1086 points in 3 dimensions; cells: 87 line, 2017 triangle; point_data=['gmsh:dim_tags']; cell_data=['gmsh:physical', 'gmsh:geometrical']; cell_sets=['null flux boundary', 'hydraulic head', 'tailings', 'starter_dam', 'erosion', 'gmsh:bounding_entities']
##
Trying to save original mesh as vtu-file (possibly not all features may be saved)
Info: VTU format cannot write cell_sets. Converting them to cell_data...
Traceback (most recent call last):
  File "/home/eloy/Documentos/Merriespruit_mesh/msh2vtu.py", line 210, in <module>
    meshio.write(output_basename + "_original.vtu", mesh, binary=not args.ascii)
  File "/home/eloy/.local/lib/python3.10/site-packages/meshio/_helpers.py", line 188, in write
    return writer(filename, mesh, **kwargs)
  File "/home/eloy/.local/lib/python3.10/site-packages/meshio/vtu/_vtu.py", line 644, in write
    mesh.cell_sets_to_data(key)
  File "/home/eloy/.local/lib/python3.10/site-packages/meshio/_mesh.py", line 328, in cell_sets_to_data
    arr[cc] = i
IndexError: index 14 is out of bounds for axis 0 with size 13

Is it a geometry issue? 

Thanks a lot.

Regards,
MC

**Comment by FrankFrank9** [comment]
I'm having the exact same issue, same error message.
Have you solved? Any idea?
Actualy I was using
`meshio convert test.msh test.vtu`
