### ISSUE TITLE
AssertionError: More than one / no 'vtkUnstructuredGrid' found!

### ISSUE THREAD

**Issue by haplav** [nschloe/meshio#138]
Some Exodus files fail to read with the following traceback:
```
Traceback (most recent call last):
  File "/opt/miniconda3/envs/meshio/bin/meshio-convert", line 133, in <module>
    _main()
  File "/opt/miniconda3/envs/meshio/bin/meshio-convert", line 16, in _main
    meshio.read(args.infile, file_format=args.input_format)
  File "/opt/miniconda3/envs/meshio/lib/python3.6/site-packages/meshio/helpers.py", line 114, in read
    out = vtk_io.read('exodus', filename)
  File "/opt/miniconda3/envs/meshio/lib/python3.6/site-packages/meshio/vtk_io.py", line 119, in read
    vtk_mesh = _read_exodusii_mesh(reader)
  File "/opt/miniconda3/envs/meshio/lib/python3.6/site-packages/meshio/vtk_io.py", line 208, in _read_exodusii_mesh
    assert len(vtk_mesh) == 1, 'More than one \'vtkUnstructuredGrid\' found!'
AssertionError: More than one 'vtkUnstructuredGrid' found!
```
(sample file to reproduce: [sevenside.exo.zip](https://github.com/nschloe/meshio/files/1437891/sevenside.exo.zip))

or
```
Traceback (most recent call last):
  File "/opt/miniconda3/envs/meshio/bin/meshio-convert", line 133, in <module>
    _main()
  File "/opt/miniconda3/envs/meshio/bin/meshio-convert", line 16, in _main
    meshio.read(args.infile, file_format=args.input_format)
  File "/opt/miniconda3/envs/meshio/lib/python3.6/site-packages/meshio/helpers.py", line 114, in read
    out = vtk_io.read('exodus', filename)
  File "/opt/miniconda3/envs/meshio/lib/python3.6/site-packages/meshio/vtk_io.py", line 119, in read
    vtk_mesh = _read_exodusii_mesh(reader)
  File "/opt/miniconda3/envs/meshio/lib/python3.6/site-packages/meshio/vtk_io.py", line 207, in _read_exodusii_mesh
    assert vtk_mesh, 'No \'vtkUnstructuredGrid\' found!'
AssertionError: No 'vtkUnstructuredGrid' found!
```
(sample file to reproduce: [hex_2_2_2.exo.zip](https://github.com/nschloe/meshio/files/1437901/hex_2_2_2.exo.zip))

**Comment by nschloe** [comment]
Fixed now.

I've actually reimplemented Exodus I/O with netCDF4 (instead of VTK) and it turned out to be a lot easier to handle. On the downside, meshio just picked up another dependency, python{3}-netcdf4. Should be available on most systems though.

Perhaps there are still some bugs left, just let me know.

**Comment by haplav** [comment]
It works for me now! Good work! Thanks!
