### ISSUE TITLE
[BUG] Xdmf TimeSeriesWriter gives ValueError when the mesh has a 'line' cell type along with any other cell type.

### ISSUE THREAD

**Issue by amit112amit** [nschloe/meshio#1398]
**Describe the bug**
When we write a mesh with a line cell type along with any other cell type using the `meshio.xdmf.TimeSeriesWriter`, an array broadcast error is raised in line 413 of `xdmf/time_series.py` because we are resizing an array in place.

**To Reproduce**
The following code reproduces the error
```python
import meshio

points = [
    [0.0, 0.0, 0.0],
    [1.0, 0.0, 0.0],
    [2.0, 0.0, 0.0]
]

cells = {
    'line': [[0, 1], [1, 2]],
    'triangle': [[0, 1, 2]]
}

with meshio.xdmf.TimeSeriesWriter('Test.xdmf') as writer:
    writer.write_points_cells(points, cells)
```
The error obtained is
```bash
Traceback (most recent call last):
  File "/home/user/Dir/mwe_1.py", line 15, in <module>
    writer.write_points_cells(points, cells)
  File "/home/user/Meshio/lib64/python3.11/site-packages/meshio/xdmf/time_series.py", line 291, in write_points_cells
    self.cells(cells, grid)
  File "/home/user/Meshio/lib64/python3.11/site-packages/meshio/xdmf/time_series.py", line 413, in cells
    c.data[:] = np.insert(c.data, 0, 2, axis=1)
    ~~~~~~^^^
ValueError: could not broadcast input array from shape (2,3) into shape (2,2)
```

**Diagnose**
The output of
```
pip freeze | grep meshio
```
is
```bash
meshio==5.3.4
```

**Did I help?**

If I was able to resolve your problem, consider [sponsoring](https://github.com/sponsors/nschloe) my work on meshio, or [buy me a coffee](https://ko-fi.com/nschloe) to say thanks.

**Comment by Pwolf-Lin** [comment]
Hello, I noticed that we both encountered the same issue with the meshio library using the same version. I was wondering if you have found a solution for it. Could you please let me know if you have any insights or if there is a workaround that you discovered? Looking forward to your response. Thank you!

**Comment by amit112amit** [comment]
Hi @Pwolf-Lin
As a workaround, I located the file `time_series.py` in my `meshio` installation and changed line 413 in that file to

```python
c.data = np.insert(c.data, 0, 2, axis=1)
```
Hope this helps!

**Comment by Pwolf-Lin** [comment]
Thank you, @amit112amit 
I have also explored an alternative approach: separating the line elements into a separate file and then using ParaView to read it. This method also achieves the desired results I was looking for.
