### ISSUE TITLE
Exodus reading error: KeyError: 'coordz'

### ISSUE THREAD

**Issue by haplav** [nschloe/meshio#141]
I get the following error with the [attached](https://github.com/nschloe/meshio/files/1457380/sevenside-quad-15.exo.zip) simple 2D Exodus mesh:

```
Traceback (most recent call last):
  File "/opt/miniconda3/envs/meshio/bin/meshio-convert", line 133, in <module>
    _main()
  File "/opt/miniconda3/envs/meshio/bin/meshio-convert", line 16, in _main
    meshio.read(args.infile, file_format=args.input_format)
  File "/opt/miniconda3/envs/meshio/lib/python3.6/site-packages/meshio/helpers.py", line 121, in read
    out = exodus_io.read(filename)
  File "/opt/miniconda3/envs/meshio/lib/python3.6/site-packages/meshio/exodus_io.py", line 72, in read
    nc.variables['coordz'][:],
KeyError: 'coordz'
```

**Comment by nschloe** [comment]
Fix released.

**Comment by haplav** [comment]
Thanks!
