### ISSUE TITLE
ValueError in conversion from gmsh msh format

### ISSUE THREAD

**Issue by massimiliano-leoni** [nschloe/meshio#174]
Converting from gmsh msh format results in the following error.

```
$ meshio-convert Mesh_medium.msh Mesh_medium.xml
Traceback (most recent call last):
  File "/home/mleoni/.local/bin/meshio-convert", line 135, in <module>
    _main()
  File "/home/mleoni/.local/bin/meshio-convert", line 18, in _main
    meshio.read(args.infile, file_format=args.input_format)
  File "/home/mleoni/.local/lib/python3.5/site-packages/meshio/helpers.py", line 121, in read
    return format_to_reader[file_format].read(filename)
  File "/home/mleoni/.local/lib/python3.5/site-packages/meshio/gmsh_io.py", line 99, in read
    out = read_buffer(f)
  File "/home/mleoni/.local/lib/python3.5/site-packages/meshio/gmsh_io.py", line 364, in read_buffer
    f, 'ElementData', cell_data_raw, int_size, data_size, is_ascii
  File "/home/mleoni/.local/lib/python3.5/site-packages/meshio/gmsh_io.py", line 274, in _read_data
    num_string_tags = int(f.readline().decode('utf-8'))
ValueError: invalid literal for int() with base 10: ''
```

**Comment by nschloe** [comment]
As usual, I need the mesh for that (or even better a minimal mesh that reproduces the error). Otherwise I cannot reproduce the bug to make sure that I fix it.

**Comment by massimiliano-leoni** [comment]
Yes, sorry. Here is a mesh that does that https://drive.google.com/open?id=1cW8N07yzCnwpe5cMb0OvvmPQ1QBLlKef .
I realized that not all the meshes I tried give the same error, some do and some don't.

**Comment by massimiliano-leoni** [comment]
Damn, it was a stupid issue then :D 
Sorry for missing it!

**Comment by nschloe** [comment]
No worries. Admittedly messages aren't very clear when it comes to parsing errors.
