### ISSUE TITLE
key error when converting from gmsh to xdmf

### ISSUE THREAD

**Issue by tanyakarn** [nschloe/meshio#191]
I have a gmsh msh file that I want to convert to xdmf, when I run `meshio-convert mesh.msh mesh.xdmf`, I get this message: 
```  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "/home/tanya/.local/bin/meshio-convert", line 135, in <module>
    _main()
  File "/home/tanya/.local/bin/meshio-convert", line 75, in _main
    field_data=field_data
  File "/home/tanya/.local/lib/python3.6/site-packages/meshio/helpers.py", line 243, in write
    field_data=field_data
  File "/home/tanya/.local/lib/python3.6/site-packages/meshio/xdmf_io.py", line 531, in write
    XdmfWriter(*args, **kwargs)
  File "/home/tanya/.local/lib/python3.6/site-packages/meshio/xdmf_io.py", line 413, in __init__
    self.cells(cells, grid)
  File "/home/tanya/.local/lib/python3.6/site-packages/meshio/xdmf_io.py", line 485, in cells
    for key, value in cells.items()
  File "/home/tanya/.local/lib/python3.6/site-packages/meshio/xdmf_io.py", line 485, in <listcomp>
    for key, value in cells.items()
KeyError: 'line'
```
I'm using the latest version of meshio installed through pip. I've attached the msh file.
[mesh.zip](https://github.com/nschloe/meshio/files/1644804/mesh.zip)

**Comment by nschloe** [comment]
Good catch! I'm looking at it now.

**Comment by nschloe** [comment]
I've fixed this via https://github.com/nschloe/meshio/pull/192. Note though that there's a bug somewhere in the ParaView/VTK/Xdmf3 that makes ParaView segfault if the mesh is in HDF5 or binary XDMF format. I've filed a bug for this [here](https://gitlab.kitware.com/paraview/paraview/issues/17945); you might want to follow up.
