### ISSUE TITLE
Python 2: Conversion to dolfin xml broken

### ISSUE THREAD

**Issue by hmella** [nschloe/meshio#196]
I have an issue converting meshes to .xml format. It seems that the problem is  in [meshio/dolfin_io.py](https://github.com/nschloe/meshio/blob/master/meshio/dolfin_io.py). A fix that worked for me is in the commit [a16c1f7](https://github.com/hmella/meshio/commit/a16c1f7a52798567389cf4f58ba2513afd8c212f?diff=unified) of my fork of the repo.

Specifically, the error message that I get is
```
Traceback (most recent call last):
  File "/usr/local/bin/meshio-convert", line 135, in <module>
    _main()
  File "/usr/local/bin/meshio-convert", line 75, in _main
    field_data=field_data
  File "/usr/local/lib/python2.7/dist-packages/meshio/helpers.py", line 194, in write
    dolfin_io.write(filename, points, cells, cell_data=cell_data)
  File "/usr/local/lib/python2.7/dist-packages/meshio/dolfin_io.py", line 248, in write
    _write_mesh(filename, points, cell_type, cells)
  File "/usr/local/lib/python2.7/dist-packages/meshio/dolfin_io.py", line 182, in _write_mesh
    tree.write(filename)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 820, in write
    serialize(write, self._root, encoding, qnames, namespaces)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 932, in _serialize_xml
    v = _escape_attrib(v, encoding)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1092, in _escape_attrib
    _raise_serialization_error(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1052, in _raise_serialization_error
    "cannot serialize %r (type %s)" % (text, type(text).__name__)
TypeError: cannot serialize {'dolfin': 'https://fenicsproject.org/'} (type dict)
```
And it can be reproduced using `meshio-convert mesh.msh mesh.xml` with the attached mesh file.
[mesh.zip](https://github.com/nschloe/meshio/files/1670443/mesh.zip)

**Comment by nschloe** [comment]
Thanks for the report!

This error seems to be specific to Python 2, which is why the tests don't catch it. If you're fine with running Python 3, I'd just skip this one. ([Python 2 isn't supported for much longer anyways.](https://pythonclock.org/))

**Comment by hmella** [comment]
Thank you!

With Python 3 everything works fine (I have no problem in using Python 3)

**Comment by nschloe** [comment]
Alright, let's just close it then.
