### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by teobo** [nschloe/meshio#21]
Hi,
get the below error message on ubuntu 14.04. I get that kind of error message as well on python console. However the file is https://www.dropbox.com/sh/i259x4vmf7e8fjt/AADFpEbb7RWPwqUtraw5exeVa (in 'angle' directory)
readable by paraview. It is binary.

thats how I installed:
1637  apt-get install python-h5py 
 1638  pip install meshio
 1639  apt-get install python-pyvtk 
 1640  apt-get install python-numpy
 1641  apt-get install python-vtk
 1642  history

 Test:
```
meshio-convert /tmp/elmermesh/angle/case0001.vtu input.msh
```
```
Traceback (most recent call last):
  File "/usr/local/bin/meshio-convert", line 64, in <module>
    _main()
  File "/usr/local/bin/meshio-convert", line 16, in _main
    meshio.read(args.infile, timestep=args.timesteps)
  File "/usr/local/lib/python2.7/dist-packages/meshio/__init__.py", line 40, in read
    return vtk_io.read('vtu', filename)
  File "/usr/local/lib/python2.7/dist-packages/meshio/vtk_io.py", line 35, in read
    cells_nodes = _read_cells_nodes(vtk_mesh)
  File "/usr/local/lib/python2.7/dist-packages/meshio/vtk_io.py", line 129, in _read_cells_nodes
    assert all(array[::num_nodes_per_cell+1] == num_nodes_per_cell)
AssertionError
```

Btw:
"Requirements

MeshIO depends on

h5py,
NumPy, and
VTK."
VTK link points to a false url...

Maybe you can help. Tia

**Comment by nschloe** [comment]
Thanks! All fixed now in 1.0.0.
