### ISSUE TITLE
MSH4

### ISSUE THREAD

**Issue by gdmcbain** [nschloe/meshio#280]
Gmsh 4.0.0 was released on Wed. 22, featuring ‘new MSH4 format’; see http://gmsh.info/CHANGELOG.txt:
> 4.0.0 (August 22, 2018): new C++, C, Python and Julia API; new MSH4 format

[MSH file format version 4](http://gmsh.info/doc/texinfo/gmsh.html#MSH-file-format-_0028version-4_0029) is generated by default in Gmsh 4, which is now the current stable release, but cannot be read with `meshio.read` which asserts that the MSH format is version 2. 

To reproduce, get say Gmsh's [tutorial/t1.geo](https://gitlab.onelab.info/gmsh/gmsh/blob/master/tutorial/t1.geo) and mesh it
```shell
gmsh -2 t1.geo
```
to produce t1.msh (attached here gzipped as [t1.msh.gz](https://github.com/nschloe/meshio/files/2322131/t1.msh.gz)).  Then
```shell
python -c 'import meshio; meshio.read("t1.msh")'
```
raises
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/users/geordie/.py3.7/skfem/lib/python3.7/site-packages/meshio/helpers.py", line 162, in read
    return format_to_reader[file_format].read(filename)
  File "/usr/local/users/geordie/.py3.7/skfem/lib/python3.7/site-packages/meshio/gmsh_io.py", line 165, in read
    mesh = read_buffer(f)
  File "/usr/local/users/geordie/.py3.7/skfem/lib/python3.7/site-packages/meshio/gmsh_io.py", line 452, in read_buffer
    data_size, is_ascii = _read_header(f, int_size)
  File "/usr/local/users/geordie/.py3.7/skfem/lib/python3.7/site-packages/meshio/gmsh_io.py", line 175, in _read_header
    assert str_list[0][0] == "2", "Need mesh format 2"
AssertionError: Need mesh format 2
```

**Comment by gdmcbain** [comment]
`test/test_gmsh` doesn't pick this up because it uses `meshio.gmsh_io.write` which writes MSH2.

**Comment by nschloe** [comment]
Geez, _another_ new mesh format out of gmsh?! Looking into it...

**Comment by gdmcbain** [comment]
I know, that was my initial reaction too; however, I'm hoping that it might be faster to read.  Profiling revealed that reading the .msh file was the bottleneck in my last finite element application.

**Comment by nschloe** [comment]
> Profiling revealed that reading the .msh file was the bottleneck in my last finite element application.

Indeed. The msh2 was not very well thought out. One big problem here was that you didn't know how many integer entities you had to read for the elements since the tags were inlined, meaning that you had to go through the file line by line. There were other things too.

**Comment by nschloe** [comment]
Alright, so #283 implements many things about msh4. Still missing are point and cell data, but that can be added later.

My verdict, now that I've checked out the format in more detail: Better, but still bad. A major problem is the fact that elements refer to the nodes not by index, but by a tag that associated with each node. The tag doesn't need to be consecutive (and usually isn't), so to fit meshio (and all other formats), one has to associate the tags with a running index, and that is expensive.

For your applications, I'd recommend using a different format. Even VTK, as old as it may be, is superior when it comes to I/O.

You might also want to check https://github.com/nschloe/optimesh.

Let's leave this open until point and cell data are implemented.

**Comment by gdmcbain** [comment]
Thank you for #283 and for the application tips.  The main reason for relying on the MSH format is that that is what is used internally by `pygmsh.generate_mesh` (nschloe/pygmsh#209, kinnala/scikit-fem#40). Also I thought that it was the only format with which the physical entities used for subdomains regions #175  and mixed boundary conditions could be generated in Gmsh/pygmsh and passed through meshio.read back to Python.  But perhaps I haven't thought carefully enough about your tips; I'll revisit them after fixing #284.

**Comment by nschloe** [comment]
@gdmcbain I'd be great if you could provide an ASCII and a binary file with NodeData and ElementData. Once those are done, we are more or less there for MSH4.

**Comment by gdmcbain** [comment]
> @gdmcbain I'd be great if you could provide an ASCII and a binary file with NodeData and ElementData. Once those are done, we are more or less there for MSH4.

Will do.  I haven't actually been using NodeData or ElementData lately, but should be able to cook something up.

Another remaining issue though, as flagged in nschloe/pygmsh#209, is 'gmsh:physical' in `cell_data`.  I think that comes from the Nodes section, unless that's changed.

**Comment by gdmcbain** [comment]
> Indeed. I had the idea of switching to VTK and would have done that if gmsh implemented binary VTK files. They don't do that right now.

Actually it seems that they do: [t1.vtk.gz](https://github.com/nschloe/meshio/files/2330233/t1.vtk.gz). 
```shell
gmsh -2 -bin -format vtk t1.geo
```

This is with Gmsh 4.0.1-git-296dd75f0, but I haven't tried it before so don't know how far back it goes.

I think the VTK output by Gmsh (binary or ASCII) only contains POINTS, CELLS, and CELL_TYPES, so no physical entities for regions #175 or mixed boundary conditions.  These are essential for a lot of finite element applications.  (Or is there some way to work around that…?)

**Comment by gdmcbain** [comment]
I attach a couple of minimal examples of physical entities, with GEO input and ASCII MSH4 output
* [point.tar.gz](https://github.com/nschloe/meshio/files/2330339/point.tar.gz)
* [segment.tar.gz](https://github.com/nschloe/meshio/files/2330340/segment.tar.gz)

After `meshio.read`, the values in `cell_data` are all `{}` though the correct keys are there.  The indices of physical entities do appear in `field_data`.

**Comment by gdmcbain** [comment]
> @gdmcbain I'd be great if you could provide an ASCII and a binary file with NodeData and ElementData.

* [ascii.tar.gz](https://github.com/nschloe/pygmsh/files/2330460/ascii.tar.gz)
* [binary.tar.gz](https://github.com/nschloe/pygmsh/files/2330461/binary.tar.gz)

I realized that I didn't know how to generate these in MSH4 from a GEO file, so adapted [demos/api/view.py](https://gitlab.onelab.info/gmsh/gmsh/blob/master/demos/api/view.py), as included.  The mesh is four nodes and two triangular elements sharing an edge and forming a square.
![nodal_data](https://user-images.githubusercontent.com/1588947/44761506-c393a280-ab86-11e8-9a4b-9bb11dc5a04b.png)
![elemental_data](https://user-images.githubusercontent.com/1588947/44761505-c2fb0c00-ab86-11e8-9e04-651e515041d9.png)

**Comment by geuzaine** [comment]
> My verdict, now that I've checked out the format in more detail: Better, but still bad. A major problem is the fact that elements refer to the nodes not by index, but by a tag that associated with each node. 

The format needs to support sparse numberings for different applications - but I hear your concern :-) 

So on the master branch we now renumber nodes/elements by default (after mesh generation - we don't renumber data that is not generated by Gmsh). This means that in your use cases the node tags will effectively behave like indices, without losing any generality. 

In practice, in your converter, once you are done reading the $Node section, just check if the numbering is dense. If it is you can then simply use the node tags as indices.

**Comment by nschloe** [comment]
@geuzaine Hi Christophe, nice to have you here!

> The format needs to support sparse numberings for different applications - [...]

This could perhaps have been implemented in a different way, for example by keeping separate tag arrays around. This approach is generally more flexible. For example MSH4 loses some of the generality of MSH2 by _grouping_ node/elements into sets rather than actually tagging them. (A node/element can only ever be in one group, but could have multiple tags.) Anyway, too late now.

> So on the master branch we now renumber nodes/elements by default (after mesh generation - we don't renumber data that is not generated by Gmsh). This means that in your use cases the node tags will effectively behave like indices, without losing any generality.

Alright, then let's wait till the next release, hopefully we should be able to save some of the computational complexity then.

**Comment by geuzaine** [comment]
I don't understand your first remark: even in MSH2 an element could only have one tag. And this was the root of the issue with the physical groups: if you wanted an element to belong to two groups, you would have to duplicate the element.

**Comment by nschloe** [comment]
> even in MSH2 an element could only have one tag.

Ah really? I seem to remember differing geometric and physical tags. Independent of what that was, separate tag arrays seem to be more flexible and computationally efficient than the grouping and entity-tagging as done in MSH4. But let's not discuss this now, the standard is already out there.

**Comment by gdmcbain** [comment]
> But let's not discuss this now, the specification is already out there.

@geuzaine has launched a forum for just such a discussion.

* https://gitlab.onelab.info/gmsh/gmsh/issues/444 ‘MSH 4.1 format’

There's also some illuminating comments on [Gmsh]:
* [‘(again) on v4 mesh format’](http://onelab.info/pipermail/gmsh/2018/012414.html)
* [‘node and element sparsity in msh4’](http://onelab.info/pipermail/gmsh/2018/012432.html)

The latter in particular explains why one might want more than one physical tag on a given element—oops! That wasn't allowed for in #304 … 

The current `meshio.read` of MSH4 more or less tries to return a `meshio.Mesh` that is like what one would get from an equivalent MSH2, which defeats the intent of MSH4 to provide for more; I wonder whether `msh4.read_buffer` should return a `Mesh` more like those extracted from Exodus II. #254
