### ISSUE TITLE
HDF5 version incompatibility

### ISSUE THREAD

**Issue by GolovPavel** [nschloe/meshio#376]
Hello. I try to create mesh and save it to xdmf file, but I'v got a error connected with version incompatibility of HDF5 (I have 1.10.4 version of HDF5, but required 1.10.0).
My version of h5py is 2.9.0 (1.10.4 version of HDF5) and version of meshio is 2.3.7.
The example below.
```python
import meshio
import pygmsh

geom = pygmsh.built_in.Geometry()
geom.add_circle(
    [0.0, 0.0, 0.0],
    1.0,
    lcar=0.1,
    num_sections=4,
    compound=True
)
mesh_data = pygmsh.generate_mesh(geom, prune_z_0=True)
p, c, _, _, _ = mesh_data
meshio.write_points_cells("mesh.xdmf", p, c)
```
The error:
```python
/usr/local/lib/python3.6/dist-packages/h5py/__init__.py:75: UserWarning: h5py is running against HDF5 1.10.0 when it was built against 1.10.4, this may cause problems
  '{0}.{1}.{2}'.format(*version.hdf5_built_version_tuple)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py", line 3267, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-a80e3d450979>", line 1, in <module>
    runfile('/home/pavel/Repositories/ascro/test/testasd.py', wdir='/home/pavel/Repositories/ascro/test')
  File "/home/pavel/Programs/pycharm-2018.3.4/helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/home/pavel/Programs/pycharm-2018.3.4/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/pavel/Repositories/ascro/test/testasd.py", line 18, in <module>
    meshio.write_points_cells("mesh.xdmf", p, c)
  File "/usr/local/lib/python3.6/dist-packages/meshio/helpers.py", line 190, in write_points_cells
    return write(filename, mesh, file_format=file_format, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/meshio/helpers.py", line 227, in write
    return interface.write(filename, mesh, *args, **_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/meshio/xdmf_io/main.py", line 468, in write
    XdmfWriter(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/meshio/xdmf_io/main.py", line 278, in __init__
    self.h5_file = h5py.File(self.h5_filename, "w")
  File "/usr/local/lib/python3.6/dist-packages/h5py/_hl/files.py", line 391, in __init__
    fapl = make_fapl(driver, libver, rdcc_nslots, rdcc_nbytes, rdcc_w0, **kwds)
  File "/usr/local/lib/python3.6/dist-packages/h5py/_hl/files.py", line 108, in make_fapl
    plist.set_libver_bounds(low, high)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5p.pyx", line 1140, in h5py.h5p.PropFAID.set_libver_bounds
ValueError: Invalid high library version bound (invalid high library version bound)
```

How can I deal with this problem? Thank you advance!

**Comment by nschloe** [comment]
This is not a meshio error, but a h5py one:
```
/usr/local/lib/python3.6/dist-packages/h5py/__init__.py:75: UserWarning: h5py is running against HDF5 1.10.0 when it was built against 1.10.4, this may cause problems
```
Looks like you need to rebuild h5py. Check their repo if it doesn't work https://github.com/h5py/h5py.
