### ISSUE TITLE
error in med to mdpa conversion

### ISSUE THREAD

**Issue by MagaFem** [nschloe/meshio#392]
[Plate.zip](https://github.com/nschloe/meshio/files/3232608/Plate.zip)
Error:

```
Traceback (most recent call last):
[Plate.zip](https://github.com/nschloe/meshio/files/3232605/Plate.zip)
[Plate.zip](https://github.com/nschloe/meshio/files/3232606/Plate.zip)
  File "/usr/local/bin/meshio-convert", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/meshio/cli.py", line 39, in main
    write(args.outfile, mesh, file_format=args.output_format)
  File "/usr/local/lib/python3.7/dist-packages/meshio/helpers.py", line 227, in write
    return interface.write(filename, mesh, *args, **_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/meshio/mdpa_io.py", line 560, in write
    _write_data(fh, "NodalData", name, dat, write_binary)
  File "/usr/local/lib/python3.7/dist-packages/meshio/mdpa_io.py", line 450, in _write_data
    fh.write("Begin " + tag + " " + name + "\n\n".encode("utf-8"))
TypeError: can only concatenate str (not "bytes") to str
```

**Comment by nschloe** [comment]
Thanks for the concise report!

**Comment by MagaFem** [comment]
Thanks for the fast fix!!!!
