### ISSUE TITLE
assert "triangle" in mesh.cells AssertionError

### ISSUE THREAD

**Issue by SiriusFuenmayor** [nschloe/meshio#454]
Hi, I am trying to convert the following msh file intro dolfin xml:

```
$MeshFormat
2.2 0 8
$EndMeshFormat
$PhysicalNames
6
2 6 "contorno"
3 1 "medula"
3 2 "hueso"
3 3 "musculo"
3 4 "grasa"
3 5 "piel"
$EndPhysicalNames
$Nodes
45422
1 47 0 0
2 45 0 0
3 42 0 0
4 34 14 0
5 -6 6 0
6 -14 6 0
7 26 14 0
...
```
and I get the following error when using meshio:

```
<meshio mesh object>
  Number of points: 45422
  Number of elements:
    quad: 3125
    wedge: 84175
  Cell data: gmsh:physical, gmsh:geometrical
WARNING:root:Dolfin's XML is a legacy format. Consider using XDMF instead.
Traceback (most recent call last):
  File "/home/turpial/.local/bin/meshio-convert", line 11, in <module>
    sys.exit(main())
  File "/home/turpial/.local/lib/python3.6/site-packages/meshio/_cli.py", line 49, in main
    write(args.outfile, mesh, file_format=args.output_format)
  File "/home/turpial/.local/lib/python3.6/site-packages/meshio/_helpers.py", line 245, in write
    return interface.write(filename, mesh, *args, **_kwargs)
  File "/home/turpial/.local/lib/python3.6/site-packages/meshio/_dolfin.py", line 203, in write
    assert "triangle" in mesh.cells
AssertionError
```

**Comment by keurfonluu** [comment]
It seems that ``meshio`` is testing whether your mesh contains triangles. I don't know Dolfin XML format but I guess that it only supports triangles (thus the assertion test). Your current mesh only contains quad.

**Comment by nschloe** [comment]
> t it only supports triangles (thus the assertion test)

Or tetrahedra, indeed. I've adapted the error message to be more informative (#455).
