### ISSUE TITLE
read mixed XDMF

### ISSUE THREAD

**Issue by gdmcbain** [nschloe/meshio#553]
It's possible to `meshio.write` an XDMF file with more than one type of `cell` and the file appears to open correctly in ParaView but `meshio.read` raises a `KeyError`.

For example, the m.w.e. from #223, minimally updated, and with a `read` appended:
```python
from numpy import array
from meshio import Mesh, write, read

points = array([[0.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, 1.0]])
cells = {"line": array([[0, 1], [1, 2], [2, 0]]), "triangle": array([[0, 1, 2]])}
write("foo.xdmf", Mesh(points, cells))
bar = read("foo.xdmf")
```
raises
```
…
  File "/home/geordie/.local/share/miniconda3/envs/scikit-fem/lib/python3.7/site-packages/meshio/_xdmf/common.py", line 118, in translate_mixed_cells
    r += xdmf_idx_to_num_nodes[data[r]] + 1
KeyError: 2
```
And similarly with the example [mwe1.xdmf.gz](https://github.com/nschloe/meshio/files/3903664/mwe1.xdmf.gz) from #539.

**Comment by gdmcbain** [comment]
Actually the problem isn't with `TopologyType="mixed"`, since
```python

**Comment by gdmcbain** [comment]
Since #564 #569, `read` in the top (mixed line–triangle) example is still failing but with a different `KeyError`:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/geordie/src/meshio/meshio/_helpers.py", line 234, in read
    return format_to_reader[file_format].read(filename)
  File "/home/geordie/src/meshio/meshio/_xdmf/main.py", line 27, in read
    return XdmfReader(filename).read()
  File "/home/geordie/src/meshio/meshio/_xdmf/main.py", line 53, in read
    return self.read_xdmf3(root)
  File "/home/geordie/src/meshio/meshio/_xdmf/main.py", line 239, in read_xdmf3
    cells = translate_mixed_cells(data)
  File "/home/geordie/src/meshio/meshio/_xdmf/common.py", line 119, in translate_mixed_cells
    r += xdmf_idx_to_num_nodes[data[r]] + 1
KeyError: 0
```

**Comment by gdmcbain** [comment]
Yes, we just need to increment `r` one more to skip the number of points in the XDMF Polyline.
