### ISSUE TITLE
prepending number of vertices in XDMF TopologyType Polyline

### ISSUE THREAD

**Issue by gdmcbain** [nschloe/meshio#599]
In #539, @dajuno wrote:

> Prepending 2 to lines breaks compatibility with the FEniCS MeshValueCollection reader for reading physical line labels from XDMF (https://fenicsproject.discourse.group/t/transitioning-from-mesh-xml-to-mesh-xdmf-from-dolfin-convert-to-meshio/412/54).
> I don't know about other applications/XDMF readers, but is your recommendation to follow your decision here (i.e., to raise the issue with FEniCS devs)?

(The problem isn't related to mutation, so I've launched this separate new issue.   It's slightly more related to #553, though the XDMF files in question aren't of `TopologyType="Mixed"`.)  

The snippet at https://fenicsproject.discourse.group/t/transitioning-from-mesh-xml-to-mesh-xdmf-from-dolfin-convert-to-meshio/412/53  :

```xml
<Topology TopologyType="Polyline" NumberOfElements="40">
   <DataItem DataType="Int" Dimensions="40 3" Format="XML" Precision="8">
       2 0 4
       2 4 5
       2 5 6
       ...
```

@dajuno, could you provide a minimal working example?  Here's a simple one based on that for #539: [539.tar.gz](https://github.com/nschloe/meshio/files/3980907/539.tar.gz).  It's like the snippet but with one Polyline of two vertices, with that number two being prepended.  It reads fine in ParaView 5.6.0 and VisIt 3.0.2.

If the polylines aren't prepended with the number, how is the reader to infer it or know where the polylines break?

_Reference:—_ http://www.xdmf.org/index.php/XDMF_Model_and_Format#Linear

**Comment by gdmcbain** [comment]
I wasn't 100% sure after rereading the *XDMF Model and Format*, so I decided to generate some XDMF with ParaView.  First I generated VTK with meshio:

```python
mwe =  Mesh(array([[0., 0., 0.],
                   [1., 0., 0.],
                   [1., 1., 0.],
                   [0., 1., 0]]),
                   {'line': array([[0, 1],
                                   [2, 3],
                                   [3, 0]])})

write('mwe.vtk', mwe)
```
opened that in ParaView 5.6.0 and 'Save Data' as 'mwe.xmf'.  This looks like so:
```xml
<?xml version="1.0" ?>
<!DOCTYPE Xdmf SYSTEM "Xdmf.dtd" []>
<Xdmf xmlns:xi="http://www.w3.org/2003/XInclude" Version="2.2">
  <Domain>
    <Grid GridType="Uniform">
      <Topology TopologyType="Polyline" Dimensions="3">
        <DataItem Dimensions="3 2" NumberType="Int" Precision="8" Format="XML">
0 1 
2 3 
3 0 
</DataItem>
      </Topology>
      <Geometry GeometryType="XYZ">
        <DataItem Dimensions="4 3" NumberType="Float" Precision="8" Format="XML">
0 0 0 
1 0 0 
1 1 0 
0 1 0 
</DataItem>
      </Geometry>
    </Grid>
  </Domain>
</Xdmf>
```

**Comment by gdmcbain** [comment]
Then I generated a mixed topology :
```python
mwe =  Mesh(array([[0., 0., 0.],
                   [1., 0., 0.],
                   [1., 1., 0.],
                   [0., 1., 0]]),
                   {'line': array([[0, 1],
                                   [2, 3],
                                   [3, 0]]),
                    'quad': array([[0, 1, 2, 3]])})
write('mwe.vtk', mwe)
```
opened in ParaView and saved as XDMF:
```xml
<?xml version="1.0" ?>
<!DOCTYPE Xdmf SYSTEM "Xdmf.dtd" []>
<Xdmf xmlns:xi="http://www.w3.org/2003/XInclude" Version="2.2">
  <Domain>
    <Grid GridType="Uniform">
      <Topology TopologyType="Mixed" Dimensions="4">
        <DataItem Dimensions="17" NumberType="Int" Precision="8" Format="XML">
2 2 0 1 2 2 2 3 2 2 
3 0 3 0 1 2 3 
</DataItem>
      </Topology>
      <Geometry GeometryType="XYZ">
        <DataItem Dimensions="4 3" NumberType="Float" Precision="8" Format="XML">
0 0 0 
1 0 0 
1 1 0 
0 1 0 
</DataItem>
      </Geometry>
    </Grid>
  </Domain>
</Xdmf>
```

**Comment by gdmcbain** [comment]
So, assuming that ParaView 5.6.0 is an authoritative writer of XDMF, I conclude that the '2'-prefix should only be written by `meshio` for `TopologyType="mixed"` and not for `TopologyType="Polyline"`.

**Comment by gdmcbain** [comment]
I note that the preceding [mixed.xmf](https://github.com/nschloe/meshio/files/3981132/mixed.xmf.txt), generated by ParaView, cannot be read by meshio.
```
>>> import meshio
>>> mesh = meshio.read('mixed.xmf')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/geordie/src/meshio/meshio/_helpers.py", line 67, in read
    return reader_map[file_format](filename)
  File "/home/geordie/src/meshio/meshio/xdmf/main.py", line 27, in read
    return XdmfReader(filename).read()
  File "/home/geordie/src/meshio/meshio/xdmf/main.py", line 48, in read
    return self.read_xdmf2(root)
  File "/home/geordie/src/meshio/meshio/xdmf/main.py", line 150, in read_xdmf2
    meshio_type = xdmf_to_meshio_type[c.attrib["TopologyType"]]
KeyError: 'Mixed'
```
This is a different error to #553 and separate from the present issue.  

meshio does read [polyline.xmf](https://github.com/nschloe/meshio/files/3981154/polyline.xmf.txt) as expected.

**Comment by gdmcbain** [comment]
Now if the example is modified to write XDMF 3 directly from meshio:
```
mwe =  Mesh(array([[0., 0., 0.],
                   [1., 0., 0.],
                   [1., 1., 0.],
                   [0., 1., 0]]),
                   {'line': array([[0, 1],
                                   [2, 3],
                                   [3, 0]])})
write('polyline.xdmf', mwe)
```
this gives [polyline.tar.gz](https://github.com/nschloe/meshio/files/3981609/polyline.tar.gz) which has `TopologyType="Polyline"` and a corresponding `DataItem Dimensions="3 3"` that looks like (under `h5dump`
```
   DATASET "data1" {
      DATATYPE  H5T_STD_I64LE
      DATASPACE  SIMPLE { ( 3, 3 ) / ( 3, 3 ) }
      DATA {
      (0,0): 2, 0, 1,
      (1,0): 2, 2, 3,
      (2,0): 2, 3, 0
      }
   }
```
i.e. has the prepended twos.

This is not rendered as intended by ParaView (5.6.0).

![polyline](https://user-images.githubusercontent.com/1588947/71143047-473a3c80-226d-11ea-9177-2bcf005c4c44.png)

which looks like
2 0
1 2
2 3
3 0

(Not sure exactly how it arrived at that, skipping the seventh int, 2.)

Anyway this is wrong; meshio should write `Topology Type="Polyline"` with a `DataItem` with 
```
0 1
2 3
3 0
```
which is exactly what we get if we write to VTK and reread in meshio.

If that VTK is read in ParaView 5.7.0 and saved as XDMF, it's saved as `Topology Type="Mixed"` with `DataItem`
```
2 2 0 1 2 2 2 3 2 2 3 0
```
which is disappointing, but not of immediate concern here.

**Comment by gdmcbain** [comment]
With #602, ParaView's rendering corresponds to the original intent of the `meshio.Mesh` written in Python.

![polyline](https://user-images.githubusercontent.com/1588947/71144611-b9f9e680-2272-11ea-938a-dcb997e3d7ac.png)

**Comment by gdmcbain** [comment]
```xml
      <Topology NumberOfElements="3" TopologyType="Polyline">
        <DataItem DataType="Int" Dimensions="3 2" Format="HDF" Precision="8">polyline.h5:/data1</DataItem>
      </Topology>
```
and `data1` is
```
      DATASET "data1" {
      DATATYPE  H5T_STD_I64LE
      DATASPACE  SIMPLE { ( 3, 2 ) / ( 3, 2 ) }
      DATA {
      (0,0): 0, 1,
      (1,0): 2, 3,
      (2,0): 3, 0
      }
   }
```
