### ISSUE TITLE
XDMF Reference attribute

### ISSUE THREAD

**Issue by gdmcbain** [nschloe/meshio#608]
The following example of XDMF from [*XDMF Modal and Format*](http://www.xdmf.org/index.php/XDMF_Model_and_Format#Geometry) (but with the `Xdmf Version` bumped to `"3.0"`) can be interpreted by ParaView but not `meshio.read`
```xml
<?xml version="1.0" ?>
<!DOCTYPE Xdmf SYSTEM "Xdmf.dtd" []>
<Xdmf Version="3.0" xmlns:xi="http://www.w3.org/2001/XInclude">
   <Domain>
       <DataItem Name="Point Data" Format="XML" Dimensions="2 4 3">
           0.0    0.0    0.0
           1.0    0.0    0.0
           1.0    1.0    0.0
           0.0    1.0    0.0
           0.0    0.0    2.0
           1.0    0.0    2.0
           1.0    1.0    2.0
           0.0    1.0    2.0
       </DataItem>
       <Grid Name="Two Quads">
           <Topology Type="Quadrilateral" NumberOfElements="2" >
               <DataItem Format="XML" 
                         DataType="Int"
                         Dimensions="2 4">
                   0 1 2 3
                   1 6 7 2
               </DataItem>
           </Topology>
           <Geometry GeometryType="XYZ">
               <DataItem Reference="XML">
                   /Xdmf/Domain/DataItem[@Name="Point Data"]
               </DataItem>
           </Geometry>
       </Grid>
   </Domain>
</Xdmf>
```
which raises
```
Traceback (most recent call last):
  File "ref.py", line 5, in <module>
    mesh = meshio.read(Path(__file__).with_suffix('.xdmf').name)
  File "/home/geordie/src/meshio/meshio/_helpers.py", line 67, in read
    return reader_map[file_format](filename)
  File "/home/geordie/src/meshio/meshio/xdmf/main.py", line 27, in read
    return XdmfReader(filename).read()
  File "/home/geordie/src/meshio/meshio/xdmf/main.py", line 52, in read
    return self.read_xdmf3(root)
  File "/home/geordie/src/meshio/meshio/xdmf/main.py", line 267, in read_xdmf3
    points = self._read_data_item(data_item)
  File "/home/geordie/src/meshio/meshio/xdmf/main.py", line 57, in _read_data_item
    dims = [int(d) for d in data_item.attrib["Dimensions"].split()]
  File "src/lxml/etree.pyx", line 2480, in lxml.etree._Attrib.__getitem__
KeyError: 'Dimensions'
```
on attempting to `._read_data_item` the element 
```xml
               <DataItem Reference="XML">
                   /Xdmf/Domain/DataItem[@Name="Point Data"]
               </DataItem>
```

Now, according to [*XDMF Model and Format*](http://www.xdmf.org/index.php/XDMF_Model_and_Format#XDMF_Elements),
> Any element in XDMF can have a Name attribute or have a Reference attribute.

The [Xdmf.dtd](https://gitlab.kitware.com/xdmf/xdmf/blob/master/Xdmf.dtd) does say that the `Dimensions` attribute is `#REQUIRED` of a `DataItem`, but presumably the DTD is wrong here when there is a `Reference` attribute.

The importance of the `Reference` attribute in a `DataItem` is that it enables the `Geometry` elements of multiple `Grid` elements #568 to refer to a common set of point coordinate data.

**Comment by gdmcbain** [comment]
More from the [*XDMF Model and Format*](http://www.xdmf.org/index.php/XDMF_Model_and_Format#XDMF_Elements):
> the Reference attribute is used to take advantage of the XPath facility 

and under [‘Function’](http://www.xdmf.org/index.php/XDMF_Model_and_Format#Function)
> In the following examples we take advantage of the XPath facility to reference DataItem elements that have been previously specified :

(see which)
