### ISSUE TITLE
Can not read VTK, VTU, XDMF with voxels

### ISSUE THREAD

**Issue by stefan-gavranovic** [nschloe/meshio#690]
I am trying to test meshio but with no success. 
I am using Paraview to export Hexahedral mesh. Formats I have tried:
* VTK - binary 
* VTU - binary
* XDMF

command:
```bash
meshio-info --input-format vtu meshBin.vtu
``` 

Error output:

```bash 
λ meshio-info --input-format vtu meshBin.vtu
Traceback (most recent call last):
  File "d:\programdata\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\programdata\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\ProgramData\Anaconda3\Scripts\meshio-info.exe\__main__.py", line 7, in <module>
  File "d:\programdata\anaconda3\lib\site-packages\meshio\_cli.py", line 111, in info
    mesh = read(args.infile, file_format=args.input_format)
  File "d:\programdata\anaconda3\lib\site-packages\meshio\_helpers.py", line 67, in read
    return reader_map[file_format](filename)
  File "d:\programdata\anaconda3\lib\site-packages\meshio\vtu\_vtu.py", line 350, in read
    reader = VtuReader(filename)
  File "d:\programdata\anaconda3\lib\site-packages\meshio\vtu\_vtu.py", line 212, in __init__
    pts = self.read_data(data_array)
  File "d:\programdata\anaconda3\lib\site-packages\meshio\vtu\_vtu.py", line 337, in read_data
    data = self.read_binary(c.text.strip(), c.attrib["type"])
  File "d:\programdata\anaconda3\lib\site-packages\meshio\vtu\_vtu.py", line 294, in read_binary
    byte_string = base64.b64decode(data[:num_header_chars])
TypeError: slice indices must be integers or None or have an __index__ method
```
Here is the zip file with all the input files:

* [mesh.zip](https://github.com/nschloe/meshio/files/4199056/mesh.zip)

**Comment by tianyikillua** [comment]
Could you please try the latest master version? Maybe it got corrected last days (I myself ran into the same error).

**Comment by nschloe** [comment]
The files contain voxels, not unstructured grids. meshio isn't build for that.

**Comment by nschloe** [comment]
Okay, turns out Paraview's XDMF writer return hexahedra (since XDMF doesn't have voxels). There were one or two read issues for this, fixed now. Is that enough for you, @stefan-gavranovic? If not, feel free to reopen and we see what we can do about voxels.

**Comment by stefan-gavranovic** [comment]
@nschloe I have tried it our and it works great. Thanks a lot for the very quick feedback!
