### ISSUE TITLE
XDMF error

### ISSUE THREAD

**Issue by tdegeus** [nschloe/meshio#827]
With a seemingly legal file
```xml
<Xdmf Version="3.0">
    <Domain>
        <Grid CollectionType="Temporal" GridType="Collection" Name="TimeSeries">
            <Grid Name="Increment 0">
                <Time Value="0"/>
                <Geometry GeometryType="XY">
                    <DataItem Dimensions="6 2" Format="HDF">mesh.h5:/coor</DataItem>
                </Geometry>)
                <Topology NumberOfElements="2" TopologyType="Quadrilateral">
                    <DataItem Dimensions="2 4" Format="HDF">mesh.h5:/conn</DataItem>
                </Topology>
            </Grid>
        </Grid>
    </Domain>
</Xdmf>
```
I'm getting
```none
meshio-info test.xdmf
Traceback (most recent call last):
  File "/Users/tdegeus/miniconda3/envs/test/bin/meshio-info", line 10, in <module>
    sys.exit(info())
  File "/Users/tdegeus/miniconda3/envs/test/lib/python3.8/site-packages/meshio/_cli/_info.py", line 15, in info
    mesh = read(args.infile, file_format=args.input_format)
  File "/Users/tdegeus/miniconda3/envs/test/lib/python3.8/site-packages/meshio/_helpers.py", line 68, in read
    return reader_map[file_format](filename)
  File "/Users/tdegeus/miniconda3/envs/test/lib/python3.8/site-packages/meshio/xdmf/main.py", line 28, in read
    return XdmfReader(filename).read()
  File "/Users/tdegeus/miniconda3/envs/test/lib/python3.8/site-packages/meshio/xdmf/main.py", line 51, in read
    return self.read_xdmf3(root)
  File "/Users/tdegeus/miniconda3/envs/test/lib/python3.8/site-packages/meshio/xdmf/main.py", line 303, in read_xdmf3
    raise ReadError("Unknown section '{}'.".format(c.tag))
meshio._exceptions.ReadError: Unknown section 'Grid'.
```

**Comment by nschloe** [comment]
Looks like a bug. Can you attach a complete example so I can play around with it?

**Comment by tdegeus** [comment]
Does this help @nschloe ?

[Archive.zip](https://github.com/nschloe/meshio/files/4751897/Archive.zip)

**Comment by nschloe** [comment]
Closing for lack of feedback. @tdegeus Feel free to reopen if Tianyi's suggestion didn't work for you.
