### ISSUE TITLE
Error when attaching cell data

### ISSUE THREAD

**Issue by baloe** [nschloe/meshio#837]
I used to be able to create a mesh and attach cell data like in this MWE, but since updating a bunch of python packages, this does no longer work:

```
#!/usr/bin/env python3

doesntwork = True

import numpy as np
import meshio


# Create mesh points

x = np.linspace(0,1.0, 6)
y = np.linspace(0,2.0,11)
z = np.linspace(0,1.4, 8)
X,Y,Z = np.meshgrid( x, y, z, indexing='ij' )
points = np.concatenate( [ X.reshape(1,-1), Y.reshape(1,-1), Z.reshape(1,-1) ], axis=0 ).T

# create cells

ilen,jlen,klen =X.shape
cellindices = np.arange( ilen*jlen*klen ).reshape( (ilen, jlen, klen) )
p = [ None for i in range(8) ]
p[0] = cellindices[:-1,:-1,:-1]; p[4] = cellindices[:-1,:-1,1: ]
p[1] = cellindices[1: ,:-1,:-1]; p[5] = cellindices[1: ,:-1,1: ]
p[2] = cellindices[1: ,1: ,:-1]; p[6] = cellindices[1: ,1: ,1: ]
p[3] = cellindices[:-1,1: ,:-1]; p[7] = cellindices[:-1,1: ,1: ]
cells = { 'hexahedron' : np.concatenate([ p_.reshape((1,-1)) for p_ in p ]).T }

# Create mesh

mesh = meshio.Mesh( points, cells )

# Add fielddata

if doesntwork:
    mesh.cell_data = { 'hexahedron' : { } }
    mesh.cell_data['hexahedron']['fieldname'] = X[:-1,:-1,:-1].reshape(-1)

# write to file

meshio.write('test.vtk', mesh)
```

This has to do with the way I add cell data, because it works with `doesntwork=False`.
Otherwise I get the following errors: 
```
Traceback (most recent call last):
  File "test_meshio.py", line 40, in <module>
    meshio.write('test.vtk', mesh)
  File "/soft/conda/envs/primeframework/lib/python3.8/site-packages/meshio/_helpers.py", line 144, in write
    return writer(filename, mesh, **kwargs)
  File "/soft/conda/envs/primeframework/lib/python3.8/site-packages/meshio/vtk/_vtk.py", line 605, in write
    if len(values.shape) == 2 and values.shape[1] == 2:
AttributeError: 'str' object has no attribute 'shape'
```

I tried vtk and med as output formats.

python 3.8.3
meshio 4.0.13 (conda-forge)

**Comment by baloe** [comment]
Ah I see, "From 4.0.0 on, mesh.cell_data is a dictionary of lists"
https://github.com/nschloe/meshio/blob/master/CHANGELOG.md

**Comment by baloe** [comment]
This works with meshio 4.x

```python
#!/usr/bin/env python3

import numpy as np
import meshio


# Create mesh point data

x = np.linspace(0,1.0, 6)
y = np.linspace(0,2.0,11)
z = np.linspace(0,1.4, 8)
X,Y,Z = np.meshgrid( x, y, z, indexing='ij' )
points = np.concatenate( [ X.reshape(1,-1), Y.reshape(1,-1), Z.reshape(1,-1) ], axis=0 ).T

# create cell data

ilen,jlen,klen =X.shape
cellindices = np.arange( ilen*jlen*klen ).reshape( (ilen, jlen, klen) )
p = [ None for i in range(8) ]
p[0] = cellindices[:-1,:-1,:-1]; p[4] = cellindices[:-1,:-1,1: ]
p[1] = cellindices[1: ,:-1,:-1]; p[5] = cellindices[1: ,:-1,1: ]
p[2] = cellindices[1: ,1: ,:-1]; p[6] = cellindices[1: ,1: ,1: ]
p[3] = cellindices[:-1,1: ,:-1]; p[7] = cellindices[:-1,1: ,1: ]
cells = np.concatenate([ p_.reshape((1,-1)) for p_ in p ]).T

# Create mesh

#cells = { 'hexahedron' : cells }   # <--- v3.x
cells = [ ( 'hexahedron', cells) ]  # <--- v4.x
mesh = meshio.Mesh( points, cells )

# Add fielddata

#mesh.cell_data = { 'hexahedron': { 'fieldname' : X[:-1,:-1,:-1].reshape(-1) } } # <--- v3.x
mesh.cell_data = { 'fieldname' : [ X[:-1,:-1,:-1].reshape(-1) ] }                # <--- v4.x

# write to file

meshio.write('test.vtk', mesh)
```
