### ISSUE TITLE
Error writing GMSH format: "Can only deal with one cell type for now"

### ISSUE THREAD

**Issue by dajuno** [nschloe/meshio#865]
Hello,

meshio 4.0.16 fails to write GMSH files.

Consider the following MWE (pygmsh demo):

```python
import pygmsh
import numpy as np

geom = pygmsh.built_in.Geometry()

# Draw a cross.
poly = geom.add_polygon([
    [ 0.0,  0.5, 0.0],
    [-0.1,  0.1, 0.0],
    [-0.5,  0.0, 0.0],
    [-0.1, -0.1, 0.0],
    [ 0.0, -0.5, 0.0],
    [ 0.1, -0.1, 0.0],
    [ 0.5,  0.0, 0.0],
    [ 0.1,  0.1, 0.0]
    ],
    lcar=0.05
)

axis = [0, 0, 1]

geom.extrude(
    poly,
    translation_axis=axis,
    rotation_axis=axis,
    point_on_axis=[0, 0, 0],
    angle=2.0 / 6.0 * np.pi
)

mesh = pygmsh.generate_mesh(geom)

import meshio

# VTK works
meshio.write("test.vtk", mesh)

# gmsh fails 
meshio.write("test.msh", mesh)
```
Fails with:

```
Traceback (most recent call last):
  File "scripts/pygmsh_demo.py", line 38, in <module>
    meshio.write("test.msh", mesh)
  File "/home/nolte/.local/lib/python3.6/site-packages/meshio/_helpers.py", line 144, in write                                               
    return writer(filename, mesh, **kwargs)
  File "/home/nolte/.local/lib/python3.6/site-packages/meshio/gmsh/main.py", line 116, in <lambda>                                           
    "gmsh": lambda f, m, **kwargs: write(f, m, "4.1", **kwargs),
  File "/home/nolte/.local/lib/python3.6/site-packages/meshio/gmsh/main.py", line 107, in write                                              
    writer.write(filename, mesh, binary=binary, float_fmt=float_fmt)
  File "/home/nolte/.local/lib/python3.6/site-packages/meshio/gmsh/_gmsh41.py", line 277, in write                                           
    write4_1(filename, mesh, float_fmt=float_fmt, binary=binary)
  File "/home/nolte/.local/lib/python3.6/site-packages/meshio/gmsh/_gmsh41.py", line 317, in write4_1                                        
    _write_nodes(fh, mesh.points, mesh.cells, float_fmt, binary)
  File "/home/nolte/.local/lib/python3.6/site-packages/meshio/gmsh/_gmsh41.py", line 369, in _write_nodes                                    
    raise WriteError("Can only deal with one cell type for now")
meshio._exceptions.WriteError: Can only deal with one cell type for now             
```

The VTK file is written correctly. The command `$ meshio-convert test.vtk test.msh` fails with the same error.

Tested with current stable versions: pygmsh (6.1.1), meshio (4.0.16), gmsh (4.6.0)

Thank you for your help!
David

**Comment by nschloe** [comment]
You'll have to remove all cell types but one. (Or submit a PR to fix this.)

**Comment by gdmcbain** [comment]
Yes, a PR would be most welcome;  this is a longstanding shortcoming. #332 

Meanwhile, a sequence of alternative makeshifts, bssed on your example:
* pygmsh builds GEO. Save that and call Gmsh directly to write MSH 4.1.
* pygmsh is doing the previous step internally but writing a temporary MSH 4.1 file which is usually ignored but the user and discarded; however, pygmsh does have an option to save this file.
* Get meshio to write MSH 2.2 and ask Gmsh to [convert](http://gmsh.info/dev/doc/texinfo/gmsh.html#index-_002dconvert-files) it to MSH 4.1.. 

I've been using the last a bit lately. Studying the MSH 4.1 produced might clarify #332

**Comment by dajuno** [comment]
Thanks for the info. I'll have a look and see what I can do to contribute
