### ISSUE TITLE
Error in reading ascii coded PLY format with vertex color attribute  

### ISSUE THREAD

**Issue by goldragoon** [nschloe/meshio#869]
While converting my 3D mesh datasets into STL file format, 
I found that meshio 4.0.16 returns error to part of my data as below.

```
meshio-convert segmesh-2-test-ascii.ply segmesh-1.stl
Traceback (most recent call last):
  File "/home/paganinist/.local/bin/meshio-convert", line 10, in <module>
    sys.exit(convert())
  File "/home/paganinist/.local/lib/python3.7/site-packages/meshio/_cli/_convert.py", line 15, in convert
    mesh = read(args.infile, file_format=args.input_format)
  File "/home/paganinist/.local/lib/python3.7/site-packages/meshio/_helpers.py", line 68, in read
    return reader_map[file_format](filename)
  File "/home/paganinist/.local/lib/python3.7/site-packages/meshio/ply/_ply.py", line 62, in read
    mesh = read_buffer(f)
  File "/home/paganinist/.local/lib/python3.7/site-packages/meshio/ply/_ply.py", line 149, in read_buffer
    cell_data_dtypes,
  File "/home/paganinist/.local/lib/python3.7/site-packages/meshio/ply/_ply.py", line 169, in _read_ascii
    for name, fmt in zip(point_data_names, point_data_formats)
  File "/home/paganinist/.local/lib/python3.7/site-packages/meshio/ply/_ply.py", line 169, in <listcomp>
    for name, fmt in zip(point_data_names, point_data_formats)
KeyError: 'uchar'
```

I figure out that those data is consisted of ascii coded PLY format with vertex color attribute.
Without vertex color attribute, it doesn't generates any erroneous situations.
Binary coded PLY format with vertex color attribute is also fine.
Here is the data : [data.zip](https://github.com/nschloe/meshio/files/4952376/data.zip)

Other libraries like MeshLab, CGAL read the file very well.
If it is not intended, I'd like to volunteer to fix it.

Thanks for your hard work and read this Issue.

**Comment by nschloe** [comment]
Never post screenshots of errors, always copy and paste. You can edit your post accordingly.
