### ISSUE TITLE
Not Proper UTF-8 Error on Recent Python Versions

### ISSUE THREAD

**Issue by CrocoDuckoDucks** [nschloe/meshio#896]
Hi, I noticed something a bit odd.

I have an Ubuntu 18.04 workstation with python 3.6.9 and meshio installed with pip3. I use meshio to import VTU files exported by [ElmerFEM](http://www.elmerfem.org/blog/). Everything works just fine:

```text
$ python3
Python 3.6.9 (default, Jul 17 2020, 12:50:27) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import meshio
>>> v = meshio.read("case_t0001.vtu")
>>> v
<meshio mesh object>
  Number of points: 17949
  Number of cells:
    tetra: 94353
    line: 284
    triangle: 7474
  Point data: pressure EigenMode1, pressure EigenMode2, pressure EigenMode3, pressure EigenMode4, pressure EigenMode5, pressure EigenMode6, pressure EigenMode7, pressure EigenMode8, pressure EigenMode9, pressure EigenMode10
  Cell data: GeometryIds
``` 

However, I also have an Arch Linux workstation, running python 3.8.5 and meshio installed from [AUR](https://aur.archlinux.org/packages/python-meshio/). The same lines, on the same VTU file, fail:

```text
$ python3
Python 3.8.5 (default, Jul 27 2020, 08:42:51) 
[GCC 10.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import meshio
>>> v = meshio.read("case_t0001.vtu")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/crocoduck/.local/lib/python3.8/site-packages/meshio/_helpers.py", line 214, in read
    return format_to_reader[file_format].read(filename)
  File "/home/crocoduck/.local/lib/python3.8/site-packages/meshio/_vtu.py", line 329, in read
    reader = VtuReader(filename)
  File "/home/crocoduck/.local/lib/python3.8/site-packages/meshio/_vtu.py", line 130, in __init__
    tree = ET.parse(filename, parser)
  File "src/lxml/etree.pyx", line 3521, in lxml.etree.parse
  File "src/lxml/parser.pxi", line 1859, in lxml.etree._parseDocument
  File "src/lxml/parser.pxi", line 1885, in lxml.etree._parseDocumentFromURL
  File "src/lxml/parser.pxi", line 1789, in lxml.etree._parseDocFromFile
  File "src/lxml/parser.pxi", line 1177, in lxml.etree._BaseParser._parseDocFromFile
  File "src/lxml/parser.pxi", line 615, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 725, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 654, in lxml.etree._raiseParseError
  File "case_t0001.vtu", line 31
lxml.etree.XMLSyntaxError: Input is not proper UTF-8, indicate encoding !
Bytes: 0xE8 0x30 0x02 0x00, line 31, column 2
```
Any idea? The VTU file I used for the experiment above can be downloaded [here](https://gofile.io/d/xqeF8p).

**Comment by nschloe** [comment]
I cannot reproduce the issue on two different machines.

**Comment by nschloe** [comment]
It does look like an lxml issue, which meshio doesn't use anymore for a long time now. Probably a borked installation.

**Comment by CrocoDuckoDucks** [comment]
I see, thanks for looking into it. I raised this with the AUR package maintainer.

**Comment by CrocoDuckoDucks** [comment]
Found the issue. I had an old version installed through `pip3` in my home folder... This solved it.

```text
$ pip3 uninstall meshio
Found existing installation: meshio 3.2.15
Uninstalling meshio-3.2.15:
  Would remove:
    /home/crocoduck/.local/bin/meshio-convert
    /home/crocoduck/.local/bin/meshio-info
    /home/crocoduck/.local/lib/python3.8/site-packages/meshio-3.2.15.dist-info/*
    /home/crocoduck/.local/lib/python3.8/site-packages/meshio/*
Proceed (y/n)? y
  Successfully uninstalled meshio-3.2.15
```
Thank you for your help.
